'use strict';
const KEY='ruta-adaptativa-v4', app=document.getElementById('app'),statusEl=document.getElementById('status');
const INTERVALS=[1,3,7,14,30,60,90], DAY=86400000;
let store;try{store=JSON.parse(localStorage.getItem(KEY))}catch{};if(!store||!Array.isArray(store.goals))store={goals:[],active:null};else try{store=normalizeImportedStore(store)}catch{store={goals:[],active:null}}
let page='home',busy=false;
const E=(t,s)=>{let e=document.createElement(t);if(s!==undefined)e.textContent=s;return e};
const B=(s,f,alt=false)=>{let b=E('button',s);b.type='button';if(alt)b.className='quiet';b.onclick=f;return b};
const block=s=>{let x=E('section');x.className='box';x.append(E('h2',s));app.append(x);return x};
const g=()=>store.goals.find(x=>x.id===store.active);
function save(){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{note('El navegador no pudo guardar el progreso.',true)}}
function note(s,bad=false){statusEl.textContent=s;statusEl.className=bad?'err':'ok'}
async function api(route,payload){let c=new AbortController(),timer=setTimeout(()=>c.abort(),100000);try{let r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:c.signal});let d=await r.json();if(!r.ok)throw Error(d.error||'Error del servidor');return d}catch(e){if(e.name==='AbortError')throw Error('La solicitud tardó demasiado; revisa el servidor antes de repetir.');if(e instanceof TypeError)throw Error('No se pudo contactar al servidor local.');throw e}finally{clearTimeout(timer)}}
async function task(label,fn){if(busy)return;busy=true;note(label);try{await fn();if(statusEl.textContent===label)note('Listo.')}catch(e){note(e?.message||String(e),true);console.error(e)}finally{busy=false}}
function nav(){app.append(B('Mis metas',()=>{page='home';render()},true));if(g())app.append(B('Mi ruta',()=>{page='dashboard';render()},true))}
function backup(){let url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'})),a=E('a');a.href=url;a.download='ruta-v4-respaldo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function normalizeImportedStore(raw){
 if(!raw||typeof raw!=='object'||!Array.isArray(raw.goals))throw policyError('INVALID_BACKUP','Este archivo no es un respaldo de Ruta v4.');
 let normalized={...raw,goals:raw.goals.map(normalizeGoal)};
 if(!normalized.goals.some(x=>x.id===normalized.active))normalized.active=normalized.goals[0]?.id||null;
 return normalized
}
function normalizeGoal(raw){
 if(!raw||typeof raw!=='object'||!raw.id)throw policyError('INVALID_GOAL','El respaldo contiene una meta inválida.');
 let nodes=(Array.isArray(raw.nodes)?raw.nodes:[]).filter(x=>x&&x.id).map(n=>({...n,prerequisites:Array.isArray(n.prerequisites)?[...n.prerequisites]:[],probe:n.probe&&typeof n.probe==='object'?{...n.probe}:null}));
 let coverage=(Array.isArray(raw.coverage)?raw.coverage:[]).filter(x=>x&&x.id).map(c=>({...c,prerequisites:Array.isArray(c.prerequisites)?[...c.prerequisites]:[],contexts:Array.isArray(c.contexts)?[...c.contexts]:[],updates:Array.isArray(c.updates)?[...c.updates]:[],dimensions:(Array.isArray(c.dimensions)?c.dimensions:[]).filter(d=>d&&d.id).map(d=>({...d,evidence:Array.isArray(d.evidence)?d.evidence.map(e=>({...e})):[]}))}));
 let learner={};for(let [id,value] of Object.entries(raw.learner&&typeof raw.learner==='object'?raw.learner:{})){let x=value&&typeof value==='object'?value:{};learner[id]={...x,level:Number.isFinite(x.level)?x.level:0,confidence:typeof x.confidence==='string'?x.confidence:'unverified',evidence:Array.isArray(x.evidence)?x.evidence.map(e=>({...e})):[],errors:Array.isArray(x.errors)?x.errors.map(e=>({...e})):[],last:x.last||null}}
 let reviews=(Array.isArray(raw.reviews)?raw.reviews:[]).filter(x=>x&&x.id).map(r=>({...r,step:Number.isFinite(r.step)?r.step:0,history:Array.isArray(r.history)?r.history.map(h=>({...h})):[],question:r.question&&typeof r.question==='object'?{...r.question}:null}));
 let lessons={};for(let [id,value] of Object.entries(raw.lessons&&typeof raw.lessons==='object'?raw.lessons:{})){let l=value&&typeof value==='object'?value:{};lessons[id]={...l};for(let key of ['check','guided','independent','integration'])lessons[id][key]=l[key]&&typeof l[key]==='object'?{...l[key]}:null}
 let session=raw.session&&typeof raw.session==='object'?{...raw.session}:{mode:'DIAGNOSTIC',node:null,stack:[],stage:'teach',tries:0};session.mode=session.mode||'DIAGNOSTIC';session.node=session.node||null;session.stack=Array.isArray(session.stack)?[...session.stack]:[];session.tries=Number.isFinite(session.tries)?session.tries:0;session.hints=Number.isFinite(session.hints)?session.hints:0;
 let repairEpisodes=(Array.isArray(raw.repairEpisodes)?raw.repairEpisodes:[]).filter(x=>x&&x.episode_id).map(normalizeRepairEpisode);
 return {...raw,nodes,coverage,learner,reviews,events:Array.isArray(raw.events)?raw.events.map(e=>({...e})):[],lessons,session,map_updates:Array.isArray(raw.map_updates)?[...raw.map_updates]:[],contextStack:Array.isArray(raw.contextStack)?raw.contextStack.map(x=>({...x,history:Array.isArray(x.history)?x.history.map(h=>({...h})):[]})):[],repairEpisodes}
}
function home(){app.replaceChildren();let b=block('Una meta, no un curso genérico'),name=E('input'),context=E('textarea');name.placeholder='Ej. Entender el tratamiento superficial';context.placeholder='Opcional: experiencia previa, sin información interna';b.append(name,context,B('Empezar ruta',()=>task('Construyendo solo el mapa inicial…',async()=>{if(name.value.trim().length<5)throw Error('Escribe una meta más concreta.');let d=await api('/api/map',{goal:name.value.trim(),context:context.value.trim()});let goal={id:crypto.randomUUID(),goal:name.value.trim(),context:context.value.trim(),nodes:d.nodes,coverage:Array.isArray(d.coverage)?d.coverage:[],map_version:d.map_version||1,map_updates:[],learner:{},lessons:{},reviews:[],events:[],session:{mode:'DIAGNOSTIC',node:null,stack:[],stage:'teach',tries:0}};store.goals.push(goal);store.active=goal.id;save();page='session';render()})));
if(store.goals.length){let list=block('Mis metas');for(let x of store.goals)list.append(B(x.goal,()=>{store.active=x.id;page='dashboard';render()}),B('Eliminar',()=>{if(confirm('¿Eliminar esta meta y sus avances?')){store.goals=store.goals.filter(z=>z.id!==x.id);if(store.active===x.id)store.active=null;save();render()}},true),E('br'))}app.append(B('Exportar respaldo',backup,true));let input=E('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{let d=normalizeImportedStore(JSON.parse(await input.files[0].text()));if(!confirm('¿Reemplazar los datos v4 de este navegador por el respaldo?'))return;store=d;save();render()}catch(e){note(e.message,true)}};app.append(E('p','Restaurar respaldo v4 (reemplaza los datos actuales):'),input)}
function coverageOf(goal,id){goal.coverage=Array.isArray(goal.coverage)?goal.coverage:[];let c=goal.coverage.find(x=>x.id===id);if(!c){let n=goal.nodes.find(x=>x.id===id)||{name:id,kind:'concept',prerequisites:[]};c={id,name:n.name,kind:n.kind,priority:'important',prerequisites:n.prerequisites||[],contexts:[],status:'UNKNOWN',confidence:0,last_evidence:null,dimensions:[{id:'conceptual',name:'Comprensión',required:true,status:'UNKNOWN',evidence:[]},{id:'direct_application',name:'Aplicación',required:true,status:'UNKNOWN',evidence:[]}],updates:[]};goal.coverage.push(c)}c.dimensions=Array.isArray(c.dimensions)?c.dimensions:[];return c}
function state(goal,id){if(!goal.learner[id])goal.learner[id]={level:0,confidence:'unverified',evidence:[],errors:[],last:null};let s=goal.learner[id];s.evidence=Array.isArray(s.evidence)?s.evidence:[];s.errors=Array.isArray(s.errors)?s.errors:[];coverageOf(goal,id);return s}
const EVIDENCE_POLICY_VERSION='evidence_policy_v1';
const REPAIR_POLICY_VERSION='microtutoring_repair_episode_v1';
const REPAIR_LIMITS=Object.freeze({max_depth:4,max_activities:6,max_diagnostics:3,max_parent_retests:2,max_transfer_checks:1});
const ALLOWED_DIMENSIONS=new Set(['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','contextual_application','interpretation','transfer','procedure','memory','self_explanation']);
const ACTIVITY_ROLES={
 diagnostic_probe:{stage:'DIAGNOSTIC',dimensions:['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','procedure','memory','self_explanation'],supports_independence:true,supports_transfer:false},
 comprehension_check:{stage:'COMPREHENSION',dimensions:['conceptual','recognition','self_explanation'],supports_independence:false,supports_transfer:false},
 guided_practice:{stage:'GUIDED',dimensions:['variables','units','equation_manipulation','method_selection','direct_application','procedure'],supports_independence:false,supports_transfer:false},
 independent_practice:{stage:'INDEPENDENT',dimensions:['variables','units','equation_manipulation','method_selection','direct_application','procedure'],supports_independence:true,supports_transfer:false},
 integration:{stage:'INTEGRATE',dimensions:['contextual_application','interpretation','transfer'],supports_independence:true,supports_transfer:true},
 spaced_review:{stage:'REVIEW',dimensions:['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','contextual_application','interpretation','procedure','memory','self_explanation'],supports_independence:true,supports_transfer:false},
 microtutor_check:{stage:'MICRO_TUTOR',dimensions:['conceptual','recognition'],supports_independence:false,supports_transfer:false},
 microtutor_guided:{stage:'MICRO_TUTOR',dimensions:['direct_application','procedure'],supports_independence:false,supports_transfer:false},
 microtutor_independent:{stage:'MICRO_TUTOR',dimensions:['direct_application','procedure'],supports_independence:true,supports_transfer:false},
 repair_diagnostic:{stage:'MICRO_TUTOR',dimensions:['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','procedure'],supports_independence:false,supports_transfer:false},
 parent_retest:{stage:'PARENT_RETEST',dimensions:['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','procedure'],supports_independence:true,supports_transfer:false},
 transfer_check:{stage:'TRANSFER_CHECK',dimensions:['contextual_application','interpretation','transfer'],supports_independence:true,supports_transfer:true},
};
const LEARNING_FAILURE_STATUSES=new Set(['PARTIAL','MISCONCEPTION']);
function uniqueDimensions(values){return [...new Set((Array.isArray(values)?values:[]).filter(x=>ALLOWED_DIMENSIONS.has(x)))]}
function kindDimensions(kind){let k=String(kind||'').toLowerCase();if(!k||k==='unknown')return [];if(/transfer/.test(k))return ['transfer','contextual_application','interpretation'];if(/context|integration|case|scenario/.test(k))return ['contextual_application','interpretation'];if(/interpret/.test(k))return ['interpretation'];if(/recognition|choice|multiple|matching|mcq/.test(k))return ['recognition'];if(/self.?explanation/.test(k))return ['conceptual','self_explanation'];if(/procedure/.test(k))return ['procedure','direct_application'];if(/calculation|problem|application|exercise/.test(k))return ['direct_application'];if(/recall|memory|retrieval/.test(k))return ['memory'];if(/explanation|concept/.test(k))return ['conceptual'];return []}
function newId(prefix){let value=globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);return prefix+'-'+value}
function policyError(code,message){let error=Error(message);error.code=code;return error}
function normalizeActivityContract(raw={}){raw=raw&&typeof raw==='object'?raw:{};return {activity_id:raw.activity_id||newId('activity'),node_id:raw.node_id||null,stage:raw.stage||'UNKNOWN',kind:raw.kind||'unknown',observable_dimensions:uniqueDimensions(raw.observable_dimensions),supports_independence:raw.supports_independence===true,supports_transfer:raw.supports_transfer===true,variant_id:raw.variant_id||null,is_novel_variant:raw.is_novel_variant===true,help_policy:raw.help_policy||'any_help_blocks_independence',role:raw.role||'unspecified',evidence_scope:raw.evidence_scope==='repair_episode'?'repair_episode':'node',episode_id:raw.episode_id||null,repair_stage:raw.repair_stage||null}}
function activityContract(question={},nodeId,role){
 let source=question&&typeof question==='object'?question:{},explicit=source.activity_contract&&typeof source.activity_contract==='object'?source.activity_contract:{},policy=ACTIVITY_ROLES[role]||{stage:'UNKNOWN',dimensions:[],supports_independence:false,supports_transfer:false};
 let kind=source.kind||'unknown',safeDimensions=kindDimensions(kind).filter(x=>policy.dimensions.includes(x)),requested=Array.isArray(explicit.observable_dimensions)?explicit.observable_dimensions:Array.isArray(source.observable_dimensions)?source.observable_dimensions:safeDimensions,declared=uniqueDimensions(requested).filter(x=>safeDimensions.includes(x));
 let requestedIndependence=Object.prototype.hasOwnProperty.call(explicit,'supports_independence')?explicit.supports_independence===true:true,requestedTransfer=Object.prototype.hasOwnProperty.call(explicit,'supports_transfer')?explicit.supports_transfer===true:source.supports_transfer===true,requestedNovelty=explicit.is_novel_variant===true||source.is_novel_variant===true||Boolean(source.novelty_flags&&Object.values(source.novelty_flags).some(Boolean)),supportsTransfer=policy.supports_transfer===true&&requestedTransfer&&requestedNovelty;
 return normalizeActivityContract({...explicit,activity_id:explicit.activity_id||source.activity_id||newId('activity'),node_id:nodeId,stage:policy.stage,kind,observable_dimensions:declared,supports_independence:policy.supports_independence===true&&requestedIndependence,supports_transfer:supportsTransfer,variant_id:explicit.variant_id||source.variant_id||null,is_novel_variant:supportsTransfer&&requestedNovelty,role,evidence_scope:explicit.evidence_scope||source.evidence_scope,episode_id:explicit.episode_id||source.episode_id,repair_stage:explicit.repair_stage||source.repair_stage})
}
function evidenceTargets(activity){return uniqueDimensions(activity&&activity.observable_dimensions)}
function resultStatus(value){return value==='CORRECT'||LEARNING_FAILURE_STATUSES.has(value)||value==='UNKNOWN'?value:'UNKNOWN'}
function isLearningFailure(event){if(event?.counts_as_learning_failure===true)return true;if(event?.counts_as_learning_failure===false)return false;return event?.phase!=='DIAGNOSTIC'&&LEARNING_FAILURE_STATUSES.has(resultStatus(event?.result??event?.status))}
function isContradiction(event){if(event?.contradicts_sufficiency===true)return true;if(event?.contradicts_sufficiency===false)return false;return LEARNING_FAILURE_STATUSES.has(resultStatus(event?.result??event?.status))}
function activityEvidence(activity,assessment={},help=0,meta={}){let contract=normalizeActivityContract(activity),rawStatus=assessment&&assessment.status,result=resultStatus(rawStatus),corrected=meta.corrected===true,helpUsed=Math.max(0,Number(help)||0),diagnostic=contract.stage==='DIAGNOSTIC'||contract.role==='diagnostic_probe'||contract.role==='repair_diagnostic',auditOnly=meta.audit_only===true,timestamp=meta.timestamp||Date.now(),contradiction=!auditOnly&&LEARNING_FAILURE_STATUSES.has(result),failure=contradiction&&!diagnostic;return {evidence_id:meta.evidence_id||newId('evidence'),attempt_id:meta.attempt_id||newId('attempt'),activity_id:contract.activity_id,node_id:contract.node_id,phase:contract.stage,activity_kind:contract.kind,result,status:result,raw_result:rawStatus==null?null:String(rawStatus),help_used:helpUsed,help:helpUsed,is_independent:!auditOnly&&result==='CORRECT'&&contract.supports_independence&&helpUsed===0&&!corrected,independent:!auditOnly&&result==='CORRECT'&&contract.supports_independence&&helpUsed===0&&!corrected,is_novel_variant:!auditOnly&&contract.supports_transfer&&contract.is_novel_variant,varied:!auditOnly&&contract.supports_transfer&&contract.is_novel_variant,observed_dimensions:auditOnly?[]:evidenceTargets(contract),error_type:assessment?.error_type||'none',error:assessment?.error_type||'none',counts_as_learning_failure:failure,contradicts_sufficiency:contradiction,evidence_role:auditOnly?'evaluation':diagnostic?'diagnostic':'learning',evidence_scope:contract.evidence_scope,episode_id:contract.episode_id,repair_stage:contract.repair_stage,evaluator_version:assessment?.evaluator_version||(corrected?'user-correction-v1':'gemini-eval-v1'),decision:meta.decision||(auditOnly?'superseded':corrected?'corrected':'accepted'),corrected,original_result:resultStatus(meta.original_result??rawStatus),corrected_result:corrected?result:null,actor:meta.actor||(corrected?'user':'evaluator'),source:meta.source||(corrected?'manual_correction':'evaluation'),correction_of:meta.correction_of||null,original_attempt_id:meta.original_attempt_id||null,timestamp,at:timestamp,policy_version:EVIDENCE_POLICY_VERSION}}
function sufficient(d){let evidence=Array.isArray(d.evidence)?d.evidence:[],lastFailure=-1;for(let i=0;i<evidence.length;i++)if(isContradiction(evidence[i]))lastFailure=i;let recent=evidence.slice(lastFailure+1).filter(x=>resultStatus(x.result??x.status)==='CORRECT');if(!recent.length)return false;if(d.id==='direct_application'||d.id==='procedure')return recent.some(x=>x.is_independent===true);if(d.id==='transfer')return recent.some(x=>x.is_independent===true&&x.is_novel_variant===true);if(d.id==='memory')return recent.some(x=>x.is_independent===true&&x.phase==='REVIEW');return true}
function deriveCoverage(c={}){let dimensions=(Array.isArray(c.dimensions)?c.dimensions:[]).map(d=>{let evidence=Array.isArray(d.evidence)?d.evidence:[],mastered=sufficient(d),hasCorrect=evidence.some(x=>resultStatus(x.result??x.status)==='CORRECT'),hasFailure=evidence.some(isContradiction);return {id:d.id,name:d.name||d.id,required:d.required!==false,status:mastered?'MASTERED':hasCorrect?'PARTIALLY_UNDERSTOOD':hasFailure?'LEARNING':'UNKNOWN',mastered}});let required=dimensions.filter(d=>d.required),done=required.filter(d=>d.mastered).length;return {dimensions,done,total:required.length,confidence:required.length?done/required.length:0,status:required.length&&done===required.length?'MASTERED':done?'PARTIALLY_UNDERSTOOD':dimensions.some(d=>d.status==='LEARNING')?'LEARNING':'UNKNOWN',mastered:required.length>0&&done===required.length}}
function syncCoverage(c){let derived=deriveCoverage(c);for(let result of derived.dimensions){let d=c.dimensions.find(x=>x.id===result.id);if(d)d.status=result.status}c.confidence=derived.confidence;c.status=derived.status;return derived}
function updateCoverage(goal,id,event){let c=coverageOf(goal,id);for(let target of event.observed_dimensions){let d=c.dimensions.find(x=>x.id===target);if(!d)continue;d.evidence=Array.isArray(d.evidence)?d.evidence:[];d.evidence.push(event)}c.last_evidence=event.timestamp;return syncCoverage(c)}
function attemptDisposition(goal,attemptId,activity,nodeId){if(!attemptId)return 'new';let events=Array.isArray(goal?.events)?goal.events:[],prior=events.find(x=>x&&x.type==='EVIDENCE'&&x.attempt_id===attemptId);if(!prior)return 'new';let sameNode=!prior.node_id||!nodeId||prior.node_id===nodeId,sameActivity=!prior.activity_id||!activity?.activity_id||prior.activity_id===activity.activity_id;return sameNode&&sameActivity?'duplicate':'collision'}
function wasAttemptApplied(goal,attemptId,activity=null,nodeId=null){return attemptDisposition(goal,attemptId,activity,nodeId)!=='new'}
function prepareRecord(goal,id,phase,answer,assessment={},help=0,activity=null,attemptId=null){
 if(!goal||typeof goal!=='object'||!Array.isArray(goal.nodes)||!goal.nodes.some(n=>n&&n.id===id))throw policyError('INVALID_NODE','El resultado no corresponde a un nodo válido.');
 if(!assessment||typeof assessment!=='object')throw policyError('INVALID_RESULT','El resultado de evaluación es inválido.');
 let contract=activity?normalizeActivityContract(activity):normalizeActivityContract({node_id:id,stage:phase,kind:'legacy_unspecified',observable_dimensions:['conceptual'],role:'legacy_unspecified'}),resolvedAttempt=attemptId||assessment._attempt_id;
 if(!resolvedAttempt)throw policyError('INVALID_ATTEMPT','El resultado no contiene attempt_id.');
 if(contract.node_id&&contract.node_id!==id)throw policyError('ACTIVITY_NODE_MISMATCH','La actividad pertenece a otro nodo.');
 let disposition=attemptDisposition(goal,resolvedAttempt,contract,id);if(disposition==='duplicate')throw policyError('DUPLICATE_ATTEMPT','Este intento ya fue aplicado.');if(disposition==='collision')throw policyError('ATTEMPT_COLLISION','El attempt_id ya pertenece a otro nodo o actividad.');
 let event=activityEvidence(contract,assessment,help,{attempt_id:resolvedAttempt,corrected:assessment._corrected===true,original_result:assessment._original_status??assessment.status,audit_only:assessment._audit_only===true,actor:assessment._actor,source:assessment._source,decision:assessment._decision,correction_of:assessment._correction_of,original_attempt_id:assessment._original_attempt_id});event.answer=String(answer||'').slice(0,700);return {contract,event}
}
function commitRecord(goal,id,prepared){let event=prepared.event;if(!goal.learner||typeof goal.learner!=='object')goal.learner={};if(!Array.isArray(goal.events))goal.events=[];if(event.evidence_scope!=='repair_episode'){let s=state(goal,id);s.last=event.timestamp;s.evidence.push(event);if(event.counts_as_learning_failure)s.errors.push({at:event.timestamp,type:event.error_type||'unknown',phase:event.phase,attempt_id:event.attempt_id});updateCoverage(goal,id,event)}goal.events.push({type:'EVIDENCE',...event});save();return event}
function record(goal,id,phase,answer,assessment={},help=0,activity=null,attemptId=null){return commitRecord(goal,id,prepareRecord(goal,id,phase,answer,assessment,help,activity,attemptId))}
function cloneData(value,fallback=null){try{return JSON.parse(JSON.stringify(value))}catch{return fallback}}
function normalizedQuestion(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9áéíóúüñ]+/gi,' ').trim().replace(/\s+/g,' ')}
function normalizeGap(raw,index=0){raw=raw&&typeof raw==='object'?raw:{};let status=['SUSPECTED','CONFIRMED','REJECTED'].includes(raw.status)?raw.status:'SUSPECTED';return {gap_id:String(raw.gap_id||`gap-${index+1}`),node_id:raw.node_id||null,concept:String(raw.concept||'Laguna por determinar'),reason:String(raw.reason||''),motivating_evidence:String(raw.motivating_evidence||raw.evidence||''),confidence:Number.isFinite(Number(raw.confidence))?Math.max(0,Math.min(1,Number(raw.confidence))):0,status}}
function normalizeEpisodeQuestion(raw={},createId=false){let q=raw&&typeof raw==='object'?raw:{};return {...q,prompt:String(q.prompt||''),reference:String(q.reference||''),kind:String(q.kind||'unknown'),activity_id:q.activity_id||(createId?newId('activity'):null)}}
function repairEvidenceHas(episode,stage,predicate=()=>true){return (Array.isArray(episode?.repair_evidence)?episode.repair_evidence:[]).some(event=>event?.repair_stage===stage&&predicate(event))}
function correctIndependent(event){return event?.result==='CORRECT'&&event?.is_independent===true}
function reconcileRepairEpisode(episode,raw={}){
 let overDiagnosticLimit=(Array.isArray(raw.suspected_gaps)&&raw.suspected_gaps.length>REPAIR_LIMITS.max_diagnostics)||(Array.isArray(raw.diagnostic_checks)&&raw.diagnostic_checks.length>REPAIR_LIMITS.max_diagnostics),hasCheck=repairEvidenceHas(episode,'CHECK',event=>event.result==='CORRECT'),hasGuided=repairEvidenceHas(episode,'GUIDED',event=>event.result==='CORRECT'),hasIndependent=repairEvidenceHas(episode,'INDEPENDENT',correctIndependent),hasParent=(episode.parent_retest?.attempts||[]).some(correctIndependent),hasTransfer=episode.transfer_check?.novelty_status==='CONFIRMED'&&(episode.transfer_check?.attempts||[]).some(event=>correctIndependent(event)&&event.is_novel_variant===true);
 if(overDiagnosticLimit){episode.status='PARTIAL';episode.close_reason=episode.close_reason||'El episodio importado excede el máximo de diagnósticos.';return episode}
 if(episode.status==='COMPLETED'&&!(hasIndependent&&hasParent&&hasTransfer)){episode.status='PARTIAL';episode.close_reason=episode.close_reason||'El episodio importado no contiene toda la evidencia requerida para COMPLETED.';return episode}
 if(['PARTIAL','FAILED','ABANDONED','COMPLETED'].includes(episode.status))return episode;
 if(episode.status==='OPEN')episode.status='DIAGNOSING';
 episode.diagnostic_index=Math.min(episode.diagnostic_index,episode.diagnostic_checks.length);
 if(episode.status==='DIAGNOSING'){episode.stage='DIAGNOSTIC';return episode}
 if(!episode.selected_gap||episode.diagnostic_index<episode.diagnostic_checks.length){episode.status='DIAGNOSING';episode.stage='DIAGNOSTIC';return episode}
 if(episode.status==='REPAIRING'){if(episode.activity_count>=REPAIR_LIMITS.max_activities){episode.status='PARTIAL';episode.close_reason=episode.close_reason||'El episodio importado alcanzó el máximo de actividades de reparación.';return episode}episode.stage=!hasCheck?'CHECK':!hasGuided?'GUIDED':'INDEPENDENT';return episode}
 if(!hasIndependent){episode.status='REPAIRING';episode.stage=!hasCheck?'CHECK':!hasGuided?'GUIDED':'INDEPENDENT';return episode}
 if(episode.status==='PARENT_RETEST'){episode.stage='PARENT_RETEST';return episode}
 if(!hasParent){episode.status='PARENT_RETEST';episode.stage='PARENT_RETEST';return episode}
 episode.status='TRANSFER_CHECK';episode.stage='TRANSFER_CHECK';return episode
}
function normalizeRepairEpisode(raw={}){
 let suspected=(Array.isArray(raw.suspected_gaps)?raw.suspected_gaps:[]).slice(0,REPAIR_LIMITS.max_diagnostics).map(normalizeGap),activities=raw.repair_activities&&typeof raw.repair_activities==='object'?raw.repair_activities:{};
 let diagnostics=(Array.isArray(raw.diagnostic_checks)?raw.diagnostic_checks:[]).slice(0,REPAIR_LIMITS.max_diagnostics).map((x,i)=>{let item=x&&typeof x==='object'?x:{};return {...item,gap_id:item.gap_id||suspected[i]?.gap_id||null,question:normalizeEpisodeQuestion(item.question||item),evidence:Array.isArray(item.evidence)?item.evidence.map(e=>({...e})):[]}});
 let repair={};for(let stage of ['CHECK','GUIDED','INDEPENDENT'])repair[stage]=activities[stage]?normalizeEpisodeQuestion(activities[stage]):null;
 let episode={...raw,episode_id:raw.episode_id||newId('repair'),parent_activity_id:raw.parent_activity_id||null,parent_attempt_id:raw.parent_attempt_id||null,parent_node_id:raw.parent_node_id||null,parent_question:cloneData(raw.parent_question,{}),parent_response:String(raw.parent_response||''),parent_evaluation:cloneData(raw.parent_evaluation,{}),parent_help_used:Math.max(0,Number(raw.parent_help_used)||0),parent_context_snapshot:cloneData(raw.parent_context_snapshot,{}),suspected_gaps:suspected,diagnostic_checks:diagnostics,diagnostic_index:Math.max(0,Number(raw.diagnostic_index)||0),selected_gap:raw.selected_gap?normalizeGap(raw.selected_gap):null,repair_activities:repair,repair_evidence:Array.isArray(raw.repair_evidence)?raw.repair_evidence.map(e=>({...e})):[],parent_retest:raw.parent_retest&&typeof raw.parent_retest==='object'?{...raw.parent_retest,question:normalizeEpisodeQuestion(raw.parent_retest.question||raw.parent_retest),attempts:Array.isArray(raw.parent_retest.attempts)?raw.parent_retest.attempts.map(e=>({...e})):[]}:null,transfer_check:raw.transfer_check&&typeof raw.transfer_check==='object'?{...raw.transfer_check,question:normalizeEpisodeQuestion(raw.transfer_check.question||raw.transfer_check),attempts:Array.isArray(raw.transfer_check.attempts)?raw.transfer_check.attempts.map(e=>({...e})):[]}:null,status:['OPEN','DIAGNOSING','REPAIRING','PARENT_RETEST','TRANSFER_CHECK','COMPLETED','PARTIAL','FAILED','ABANDONED'].includes(raw.status)?raw.status:'OPEN',stage:raw.stage||'DIAGNOSTIC',activity_count:Math.max(0,Number(raw.activity_count)||0),current_help_used:Math.max(0,Number(raw.current_help_used)||0),hint_history:Array.isArray(raw.hint_history)?raw.hint_history.map(x=>({...x})):[],created_at:typeof raw.created_at==='number'&&Number.isFinite(raw.created_at)?raw.created_at:null,closed_at:raw.closed_at||null,close_reason:raw.close_reason||null,context_history:Array.isArray(raw.context_history)?raw.context_history.map(x=>({...x})):[],policy_version:raw.policy_version||REPAIR_POLICY_VERSION,limits:{...(raw.limits&&typeof raw.limits==='object'?raw.limits:{}),...REPAIR_LIMITS}};
 return reconcileRepairEpisode(episode,raw)
}
function repairEpisodes(goal){if(!Array.isArray(goal.repairEpisodes))goal.repairEpisodes=[];return goal.repairEpisodes}
function repairEpisode(goal,episodeId){return repairEpisodes(goal).find(x=>x&&x.episode_id===episodeId)||null}
function repairQuestionFingerprint(question,episodeId=''){let q=question&&typeof question==='object'?question:{},context=q.episode_id||q.context_id||episodeId||null;return JSON.stringify({activity_id:q.activity_id||null,prompt:normalizedQuestion(q.prompt),kind:String(q.kind||'unknown').trim().toLowerCase(),episode_id:context,parent_activity_id:q.parent_activity_id||null})}
function repairActivityRelation(a,b,episodeId=''){if(!a||!b)return 'INDETERMINATE';let left={activity_id:a.activity_id||null,prompt:normalizedQuestion(a.prompt),kind:String(a.kind||'').trim().toLowerCase(),episode_id:a.episode_id||a.context_id||episodeId||null,parent_activity_id:a.parent_activity_id||null},right={activity_id:b.activity_id||null,prompt:normalizedQuestion(b.prompt),kind:String(b.kind||'').trim().toLowerCase(),episode_id:b.episode_id||b.context_id||episodeId||null,parent_activity_id:b.parent_activity_id||null};if(left.activity_id&&right.activity_id&&left.activity_id===right.activity_id)return 'EQUIVALENT';if(!left.prompt||!right.prompt)return 'INDETERMINATE';if(left.prompt===right.prompt)return 'EQUIVALENT';if(!left.kind||!right.kind||left.kind==='unknown'||right.kind==='unknown')return 'INDETERMINATE';return 'DISTINCT'}
function equivalentRepairActivity(a,b,episodeId=''){return repairActivityRelation(a,b,episodeId)==='EQUIVALENT'}
function prepareRepairPlan(plan,parentQuestion,episodeId){
 plan=plan&&typeof plan==='object'?plan:{};let rawGaps=Array.isArray(plan.suspected_gaps)?plan.suspected_gaps:[],rawDiagnostics=Array.isArray(plan.diagnostic_checks)?plan.diagnostic_checks:[];if(rawGaps.length>REPAIR_LIMITS.max_diagnostics||rawDiagnostics.length>REPAIR_LIMITS.max_diagnostics)throw policyError('DIAGNOSTIC_LIMIT','El plan excede el máximo de tres diagnósticos.');let suspected=rawGaps.map((x,i)=>({...normalizeGap(x,i),status:'SUSPECTED'}));if(!suspected.length)suspected=[normalizeGap({gap_id:'gap-1',concept:'Laguna relacionada',reason:'La evaluación del problema padre requiere una comprobación acotada.',motivating_evidence:'Fallo del problema padre',confidence:0,status:'SUSPECTED'},0)];if(new Set(suspected.map(x=>x.gap_id)).size!==suspected.length)throw policyError('DUPLICATE_GAP','El diagnóstico repite una laguna dentro del episodio.');
 let diagnosticChecks=rawDiagnostics.map((item,i)=>{let raw=item&&typeof item==='object'?item:{},question=normalizeEpisodeQuestion(raw.question||raw,true);return {gap_id:raw.gap_id||suspected[i]?.gap_id||suspected[0].gap_id,question,evidence:[]}});
 if(!diagnosticChecks.length)diagnosticChecks=[{gap_id:suspected[0].gap_id,question:normalizeEpisodeQuestion(plan.check||{},true),evidence:[]}];
 let source=plan.repair_activities&&typeof plan.repair_activities==='object'?plan.repair_activities:{CHECK:plan.check,GUIDED:plan.guided,INDEPENDENT:plan.independent},repair={};for(let stage of ['CHECK','GUIDED','INDEPENDENT'])repair[stage]=normalizeEpisodeQuestion(source[stage]||{},true);
 let required=[...diagnosticChecks.map(x=>x.question),repair.CHECK,repair.GUIDED,repair.INDEPENDENT];if(required.some(q=>!normalizedQuestion(q.prompt)))throw policyError('INVALID_REPAIR_PLAN','La microtutoría no contiene todas las actividades requeridas.');
 let parent=normalizeEpisodeQuestion(parentQuestion||{},true),seen=[];for(let q of [parent,...required]){if(seen.some(prev=>repairActivityRelation(prev,q,episodeId)!=='DISTINCT'))throw policyError('DUPLICATE_REPAIR_ACTIVITY','La microtutoría repite una actividad equivalente o no aporta datos suficientes para demostrar diferencia.');seen.push(q)}
 let parentRetest=normalizeEpisodeQuestion(plan.parent_retest||{},true),transfer=normalizeEpisodeQuestion(plan.transfer_check||{},true),parentRelation=repairActivityRelation(parent,parentRetest,episodeId);if(!normalizedQuestion(parentRetest.prompt))throw policyError('INVALID_PARENT_RETEST','Falta el reintento del problema padre.');if(parentRelation==='EQUIVALENT')throw policyError('DUPLICATE_PARENT_RETEST','El reintento debe ser una versión nueva relacionada con el padre.');if(parentRelation==='INDETERMINATE')throw policyError('INDETERMINATE_PARENT_RETEST','No hay datos suficientes para distinguir el reintento del problema padre.');if(plan.transfer_novelty_status==='CONFIRMED'&&(!normalizedQuestion(transfer.prompt)||!String(plan.transfer_novelty_basis||'').trim()))throw policyError('INVALID_TRANSFER_CHECK','La transferencia confirmada requiere pregunta y fundamento de novedad.');
 let transferRelations=seen.concat(parentRetest).map(q=>repairActivityRelation(q,transfer,episodeId)),noveltyStatus=plan.transfer_novelty_status==='CONFIRMED'&&String(plan.transfer_novelty_basis||'').trim()&&normalizedQuestion(transfer.prompt)&&transferRelations.every(relation=>relation==='DISTINCT')?'CONFIRMED':'INDETERMINATE';
 return {suspected_gaps:suspected,diagnostic_checks:diagnosticChecks,repair_activities:repair,parent_retest:{question:parentRetest,attempts:[]},transfer_check:{question:transfer,attempts:[],novelty_status:noveltyStatus,novelty_basis:String(plan.transfer_novelty_basis||''),reason:noveltyStatus==='CONFIRMED'?null:'No se pudo demostrar novedad significativa.'}}
}
function createRepairEpisode(goal,parent,plan={}){
 if(!goal||!Array.isArray(goal.nodes)||!goal.nodes.some(n=>n.id===parent?.node_id))throw policyError('INVALID_NODE','El episodio no corresponde a un nodo válido.');let original=(Array.isArray(goal.events)?goal.events:[]).find(x=>x&&x.type==='EVIDENCE'&&x.attempt_id===parent?.attempt_id&&x.activity_id===parent?.activity_id&&x.node_id===parent?.node_id);if(!original)throw policyError('MISSING_PARENT_EVIDENCE','El episodio requiere la evidencia original del problema padre.');if(!isLearningFailure(original))throw policyError('INVALID_PARENT_EVIDENCE','Solo un fallo de aprendizaje del problema padre puede abrir un episodio.');let episodeId=newId('repair'),prepared=prepareRepairPlan(plan,parent.question,episodeId),created=normalizeRepairEpisode({episode_id:episodeId,parent_activity_id:parent.activity_id,parent_attempt_id:parent.attempt_id,parent_node_id:parent.node_id,parent_question:cloneData(parent.question,{}),parent_response:parent.response,parent_evaluation:cloneData(parent.evaluation,{}),parent_help_used:parent.help_used,parent_context_snapshot:cloneData(parent.context_snapshot,{}),...prepared,status:'DIAGNOSING',stage:'DIAGNOSTIC',created_at:Date.now(),policy_version:REPAIR_POLICY_VERSION});repairEpisodes(goal).push(created);return created
}
function selectRepairGap(episode){let confirmed=episode.suspected_gaps.find(x=>x.status==='CONFIRMED'),uncertain=episode.suspected_gaps.filter(x=>x.status!=='REJECTED').sort((a,b)=>b.confidence-a.confidence);episode.selected_gap=cloneData(confirmed||uncertain[0]||null,null);return episode.selected_gap}
function episodeActivity(episode){
 if(!episode)return null;let role,question,phase;
 if(episode.status==='DIAGNOSING'){let check=episode.diagnostic_checks[episode.diagnostic_index];if(!check)return null;role='repair_diagnostic';question=check.question;phase='DIAGNOSTIC'}
 else if(episode.status==='REPAIRING'){phase=episode.stage;role=phase==='CHECK'?'microtutor_check':phase==='GUIDED'?'microtutor_guided':'microtutor_independent';question=episode.repair_activities[phase]}
 else if(episode.status==='PARENT_RETEST'){phase='PARENT_RETEST';role='parent_retest';question=episode.parent_retest?.question}
 else if(episode.status==='TRANSFER_CHECK'){phase='TRANSFER_CHECK';role='transfer_check';question=episode.transfer_check?.question}else return null;
 if(!question||!question.activity_id)return null;let source={...question,activity_id:question.activity_id,episode_id:episode.episode_id,repair_stage:phase,evidence_scope:episode.status==='DIAGNOSING'||episode.status==='REPAIRING'?'repair_episode':'node'};if(role==='transfer_check'){source.supports_transfer=episode.transfer_check.novelty_status==='CONFIRMED';source.is_novel_variant=source.supports_transfer;source.novelty_flags=source.supports_transfer?{meaningful_context_change:true}:{};source.observable_dimensions=['transfer']}
 return {phase,role,question,activity:activityContract(source,episode.parent_node_id,role)}
}
function closeRepairEpisode(goal,episode,status,reason){if(episode.closed_at)return episode;let at=Date.now();episode.status=status;episode.closed_at=at;episode.close_reason=reason||null;goal.events=Array.isArray(goal.events)?goal.events:[];goal.events.push({type:'REPAIR_EPISODE_CLOSED',episode_id:episode.episode_id,status,reason:reason||null,at});while(topContext(goal)?.episode_id===episode.episode_id)popContext(goal,status,reason);save();return episode}
function transitionRepairEpisode(goal,episode,event){
 episode.current_help_used=0;
 if(episode.status==='DIAGNOSING'){let check=episode.diagnostic_checks[episode.diagnostic_index];check.evidence.push(event);let gap=episode.suspected_gaps.find(x=>x.gap_id===check.gap_id);if(gap){if(event.result==='CORRECT')gap.status='REJECTED';else if(LEARNING_FAILURE_STATUSES.has(event.result))gap.status='CONFIRMED'}episode.diagnostic_index++;if(episode.diagnostic_index>=episode.diagnostic_checks.length||episode.diagnostic_index>=REPAIR_LIMITS.max_diagnostics){if(!selectRepairGap(episode))return closeRepairEpisode(goal,episode,'PARTIAL','No fue posible seleccionar una laguna prioritaria.');episode.status='REPAIRING';episode.stage='CHECK'}return episode}
 if(episode.status==='REPAIRING'){episode.activity_count++;episode.repair_evidence.push(event);if(event.result==='CORRECT'){if(episode.stage==='CHECK')episode.stage='GUIDED';else if(episode.stage==='GUIDED')episode.stage='INDEPENDENT';else if(event.is_independent===true){episode.status='PARENT_RETEST';episode.stage='PARENT_RETEST'}}if(episode.activity_count>=REPAIR_LIMITS.max_activities&&episode.status==='REPAIRING')return closeRepairEpisode(goal,episode,'PARTIAL','Se alcanzó el máximo de actividades de reparación.');return episode}
 if(episode.status==='PARENT_RETEST'){episode.parent_retest.attempts.push(event);if(correctIndependent(event)){episode.status='TRANSFER_CHECK';episode.stage='TRANSFER_CHECK';if(episode.transfer_check?.novelty_status!=='CONFIRMED'||!normalizedQuestion(episode.transfer_check?.question?.prompt))return closeRepairEpisode(goal,episode,'PARTIAL','El reintento padre fue correcto, pero la transferencia quedó INDETERMINATE porque no se pudo demostrar una variante novedosa.')}else if(episode.parent_retest.attempts.length>=REPAIR_LIMITS.max_parent_retests)return closeRepairEpisode(goal,episode,'PARTIAL','El problema padre siguió sin resolverse de forma independiente tras dos reintentos.');return episode}
 if(episode.status==='TRANSFER_CHECK'){episode.transfer_check.attempts.push(event);if(episode.transfer_check.novelty_status!=='CONFIRMED')return closeRepairEpisode(goal,episode,'PARTIAL','La novedad de la variante quedó indeterminada.');let completed=event.result==='CORRECT'&&event.is_independent===true&&event.is_novel_variant===true;return closeRepairEpisode(goal,episode,completed?'COMPLETED':'PARTIAL',completed?'Reparación, reintento padre y transferencia verificados.':'La variante no aportó evidencia independiente, novedosa y correcta.')}
 return episode
}
function validateRepairTransition(goal,result,prepared){let episode=repairEpisode(goal,result?._episode_id);if(!episode)throw policyError('INVALID_REPAIR_EPISODE','No existe el episodio de reparación.');let current=episodeActivity(episode);if(!current||current.phase!==result._repair_stage||prepared.contract.activity_id!==current.activity.activity_id||prepared.contract.episode_id!==episode.episode_id||prepared.contract.repair_stage!==current.phase||prepared.contract.evidence_scope!==current.activity.evidence_scope)throw policyError('INVALID_REPAIR_STAGE','El resultado no corresponde a la etapa activa del episodio.');if(episode.status==='REPAIRING'&&episode.activity_count>=REPAIR_LIMITS.max_activities)throw policyError('REPAIR_LIMIT','El episodio alcanzó su límite de actividades.');if(episode.status==='PARENT_RETEST'&&episode.parent_retest.attempts.length>=REPAIR_LIMITS.max_parent_retests)throw policyError('PARENT_RETEST_LIMIT','El episodio alcanzó su límite de reintentos.');if(episode.status==='TRANSFER_CHECK'&&episode.transfer_check.attempts.length>=REPAIR_LIMITS.max_transfer_checks)throw policyError('TRANSFER_LIMIT','El episodio alcanzó su límite de transferencia.');return episode}
function nextIntervention(goal,id,phase,result){let e=result?.error_type||'none',c=coverageOf(goal,id);if(result?.status==='CORRECT')return phase==='INTEGRATE'?'SPACED_REVIEW':'ADVANCE';if(e==='prerequisite')return 'PREREQUISITE';if(['algebra','arithmetic','units','formula_selection','variable_identification'].includes(e))return 'TARGETED_MICRO';if(e==='conceptual')return 'EXPLAIN_THEN_MICRO';if(e==='memory')return 'RETRIEVAL_REPAIR';if(e==='transfer'||e==='application')return 'CONTEXTUAL_PRACTICE';return c.status==='LEARNING'?'GUIDED_REPAIR':'TARGETED_MICRO'}
function originalQuestion(goal,id,phase){let l=goal.lessons[id];return phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:phase==='INTEGRATE'?l.integration:l.independent}
function openIntervention(goal,id,phase,answer,result,event){let decision=nextIntervention(goal,id,phase,result),q=originalQuestion(goal,id,phase),node=goal.nodes.find(x=>x.id===id),nearby=(node?.prerequisites||[]).map(pid=>goal.nodes.find(x=>x.id===pid)).filter(Boolean).map(x=>({id:x.id,name:x.name,outcome:x.outcome,kind:x.kind})),snapshot={mode:goal.session.mode,node:goal.session.node,stack:[...(goal.session.stack||[])],stage:goal.session.stage,tries:goal.session.tries};task('Preparando una intervención específica…',async()=>{let allowed=canPushContext(goal,{});if(!allowed.ok)throw policyError(allowed.reason,'No se puede abrir otro contexto de reparación.');let plan=await api('/api/context/create',{question:q,answer,feedback:result.feedback,error_type:result.error_type,parent_node_id:id,nearby_prerequisites:nearby});let episode=createRepairEpisode(goal,{activity_id:event.activity_id,attempt_id:event.attempt_id,node_id:id,question:q,response:answer,evaluation:{status:event.result,error_type:event.error_type,feedback:result.feedback||''},help_used:event.help_used,context_snapshot:snapshot},plan);pushContext(goal,{context_id:newId('context'),episode_id:episode.episode_id,parent_context_id:null,status:'ACTIVE',history:[]});goal.events.push({type:'REPAIR_EPISODE_OPENED',episode_id:episode.episode_id,parent_attempt_id:event.attempt_id,parent_node_id:id,decision,at:Date.now()});save();render()})}
const verified=(goal,id)=>deriveCoverage(coverageOf(goal,id)).mastered;
function relevant(goal){let nodes=goal.nodes,byId=Object.fromEntries(nodes.map(n=>[n.id,n]));let out=[];let open=new Set(nodes.map(n=>n.id));while(open.size){let ready=nodes.filter(n=>open.has(n.id)&&n.prerequisites.every(d=>!open.has(d)||!byId[d]));if(!ready.length)break;ready.sort((a,b)=>a.level-b.level);for(let n of ready){out.push(n);open.delete(n.id)}}return out}
function nextNode(goal){return relevant(goal).find(n=>!verified(goal,n.id))||null}
function masteredCount(goal){return goal.nodes.filter(n=>verified(goal,n.id)).length}
function nextLearningAction(goal){let s=goal.session;if(s.mode==='TEACH')return 'EXPLAIN';if(s.mode==='COMPREHENSION')return 'CHECK';if(s.mode==='GUIDED')return 'GUIDED_PRACTICE';if(s.mode==='INDEPENDENT')return 'INDEPENDENT_PRACTICE';if(s.mode==='INTEGRATE')return 'INTEGRATE_WITH_GOAL';if(s.mode==='REVIEW')return 'SPACED_REVIEW';return 'PROBE_PREREQUISITE'}
function prerequisite(goal,id,visited=new Set()){if(visited.has(id))return null;visited.add(id);let n=goal.nodes.find(n=>n.id===id);if(!n)return null;for(let dep of n.prerequisites){let prior=prerequisite(goal,dep,visited);if(prior)return prior;if(!verified(goal,dep))return dep}return null}
function progressDiscrepancy(goal,id){let learner=goal?.learner?.[id]||{},progress=deriveCoverage((Array.isArray(goal?.coverage)?goal.coverage:[]).find(x=>x&&x.id===id)||{}),level=Number.isFinite(learner.level)?learner.level:0;return {node_id:id,legacy_level:level,derived_status:progress.status,inconsistent:(level>0&&progress.status==='UNKNOWN')||(level<3&&progress.mastered)}}
function derivedStartMode(goal,id){let c=(Array.isArray(goal.coverage)?goal.coverage:[]).find(x=>x&&x.id===id),progress=deriveCoverage(c||{});if(progress.mastered)return 'DIAGNOSTIC';let conceptual=progress.dimensions.find(x=>x.id==='conceptual'),direct=progress.dimensions.find(x=>x.id==='direct_application'||x.id==='procedure');if(conceptual?.mastered&&direct&&!direct.mastered)return 'GUIDED';if(conceptual?.mastered)return 'COMPREHENSION';return 'TEACH'}
function startTeach(goal,id){let s=goal.session,dep=prerequisite(goal,id);if(dep&&dep!==id){if(!s.stack.includes(id))s.stack.push(id);id=dep}let discrepancy=progressDiscrepancy(goal,id),mode=derivedStartMode(goal,id);s.node=id;s.mode=mode;s.stage='teach';s.tries=0;if(discrepancy.inconsistent){goal.events=Array.isArray(goal.events)?goal.events:[];goal.events.push({type:'PROGRESS_DISCREPANCY',at:Date.now(),...discrepancy})}save();page=mode==='DIAGNOSTIC'?'dashboard':'session';render()}
function nextAfterLesson(goal){let s=goal.session,prev=s.stack.pop();s.node=null;s.tries=0;if(prev&&!verified(goal,prev)){startTeach(goal,prev);return}s.mode='DIAGNOSTIC';save();render()}
function schedule(goal,id){goal.reviews=Array.isArray(goal.reviews)?goal.reviews:[];if(!goal.reviews.some(x=>x.id===id))goal.reviews.push({id,due:Date.now()+DAY,step:0,question:null,history:[]});save()}
function dashboard(){let goal=g();if(!goal){page='home';render();return}goal.reviews=Array.isArray(goal.reviews)?goal.reviews:[];app.replaceChildren();nav();let b=block(goal.goal),due=goal.reviews.filter(r=>r.due<=Date.now());b.append(E('p',`Hoy: ${due.length} repasos · ${masteredCount(goal)} habilidades demostradas · ${goal.nodes.length} en el mapa.`),B('Seguir aprendiendo',()=>{page='session';render()}),B(`Repasar (${due.length})`,()=>{if(!due.length){note('Aún no hay repasos pendientes.');return}goal.session.mode='REVIEW';goal.session.node=due[0].id;save();page='session';render()}));let list=block('Cobertura del objetivo');for(let n of relevant(goal)){let c=coverageOf(goal,n.id),progress=deriveCoverage(c),mark=progress.mastered?'✓':progress.status==='UNKNOWN'?'○':'→';list.append(E('p',`${mark} ${n.name} · ${progress.status} · ${progress.dimensions.filter(d=>d.required).map(d=>d.id+':'+d.status).join(', ')} · ${n.outcome}`))}app.append(B('Guardar respaldo',backup,true))}
async function session(){let goal=g();if(!goal){page='home';render();return}let s=goal.session;app.replaceChildren();nav();let b=block(goal.goal),action=nextLearningAction(goal);
if(s.mode==='DIAGNOSTIC'){let n=nextNode(goal);if(!n){b.append(E('p','Por ahora recorrimos esta ruta. Puedes practicar y revisar conceptos después.'));return}s.node=n.id;save();let p=b.appendChild(E('p',`Antes de avanzar, veamos si ya conoces «${n.name}». Si nunca lo has visto, te lo enseño.`));renderQuestion(b,n.probe,n.id,'DIAGNOSTIC','diagnostic_probe');b.append(B('No sé; enséñamelo',()=>{let activity=activityContract(n.probe,n.id,'diagnostic_probe');record(goal,n.id,'DIAGNOSTIC','No sé',{status:'UNKNOWN',error_type:'lack_of_exposure'},0,activity,newId('attempt'));startTeach(goal,n.id)},true));return}
let n=goal.nodes.find(x=>x.id===s.node);if(!n){s.mode='DIAGNOSTIC';render();return}let coverage=coverageOf(goal,n.id),progress=deriveCoverage(coverage);b.append(E('p',`Ahora: ${n.name} · ${action}`),E('p',`Cobertura: ${progress.status} · ${progress.dimensions.filter(d=>d.required).map(d=>d.name+'='+d.status).join(', ')}`));if(s.mode==='REVIEW'){await reviewView(b,goal,n);return}
if(!goal.lessons[n.id]){b.append(E('p','Preparando solo esta microlección…'));await task('Preparando una explicación breve…',async()=>{let parent=s.stack[s.stack.length-1],p=goal.nodes.find(x=>x.id===parent);goal.lessons[n.id]=await api('/api/lesson',{goal:goal.goal,name:n.name,parent:p?.name||goal.goal});save();render()});return}
let l=goal.lessons[n.id];
if(s.mode==='TEACH'){b.append(E('h3','Una idea a la vez'),E('p',l.explanation),E('p','Ejemplo'),E('pre',l.example),E('p',`Error habitual: ${l.common_error}`));b.append(B('Ahora lo intento',()=>{s.mode='COMPREHENSION';state(goal,n.id).level=Math.max(1,state(goal,n.id).level);save();render()}));return}
let phase=s.mode,question=phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:(phase==='INDEPENDENT'||phase==='CHALLENGE')?l.independent:l.integration,role=phase==='COMPREHENSION'?'comprehension_check':phase==='GUIDED'?'guided_practice':(phase==='INDEPENDENT'||phase==='CHALLENGE')?'independent_practice':'integration';
renderQuestion(b,question,n.id,phase,role);
if(phase==='GUIDED')b.append(B('Dame una pista',()=>{let x=E('p',`Pista: ${l.common_error} Piensa qué dato falta para decidir.`);b.append(x);s.hints=(s.hints||0)+1;save()},true));
if(phase==='COMPREHENSION')b.append(B('No lo entendí; vuelve al ejemplo',()=>{s.mode='TEACH';save();render()},true));
}
function renderQuestion(box,question,id,phase,role='unspecified'){
 if(!question||typeof question!=='object'||!String(question.prompt||'').trim()){box.append(E('p','La actividad no está disponible porque sus datos están incompletos.'));return {ok:false,error:'INVALID_QUESTION'}}
 let goal=g(),answer=E('textarea'),feedback=E('div'),activity=activityContract(question,id,role),attemptId=newId('attempt');box.append(E('h3',question.prompt));
 answer.placeholder='Tu idea y por qué. No hace falta que sea perfecta.';
 let submit=B('Compartir mi intento',()=>task('Analizando tu razonamiento…',async()=>{
  let text=answer.value.trim();if(!text)throw Error('Escribe una idea o elige «No sé».');
  let assessment=await api('/api/evaluate',{question,answer:text,phase,attempt_id:attemptId,activity});answer.disabled=true;
  feedback.replaceChildren(E('p',assessment.feedback));
  if(assessment.hint)feedback.append(E('p',`Pista: ${assessment.hint}`));
  let result=changes=>({...assessment,...changes,_attempt_id:attemptId,_activity:activity,_original_status:assessment.status});
   let correctionId=newId('attempt'),decisionApplied=false,run=fn=>{if(decisionApplied){note('Esta decisión ya fue aplicada. Inicia una nueva corrección si es necesario.',true);return false}try{let applied=fn();if(applied){decisionApplied=true;continueButton.disabled=true;correctionButton.disabled=true}return applied}catch(e){if(e?.code==='DUPLICATE_ATTEMPT'||e?.code==='ATTEMPT_COLLISION'){note(e.message,true);return false}throw e}},continueButton=B('Continuar',()=>run(()=>applyResult(goal,id,phase,text,result({_corrected:false,_decision:'accepted'})))),correctionButton=B('Corregir evaluación',()=>run(()=>{let ok=confirm('¿Tu respuesta demuestra comprensión?');return applyManualCorrection(goal,id,phase,text,result({_corrected:false,_decision:'superseded'}),ok?'CORRECT':'PARTIAL',correctionId)}),true);
  feedback.append(continueButton,correctionButton);
 }));box.append(answer,submit,feedback);return {ok:true,answer,submit,feedback,activity,attemptId}
}
function validateTransition(goal,id,phase,result,prepared){
 if(!goal.session||typeof goal.session!=='object')throw policyError('INVALID_SESSION','La sesión asociada al resultado es inválida.');
 let expected={DIAGNOSTIC:'DIAGNOSTIC',COMPREHENSION:'COMPREHENSION',GUIDED:'GUIDED',INDEPENDENT:'INDEPENDENT',CHALLENGE:'INDEPENDENT',INTEGRATE:'INTEGRATE',REVIEW:'REVIEW',MICRO_TUTOR:'MICRO_TUTOR',PARENT_RETEST:'PARENT_RETEST',TRANSFER_CHECK:'TRANSFER_CHECK'}[phase];if(!expected||prepared.contract.stage!==expected)throw policyError('INVALID_PHASE','La fase no corresponde al contrato de la actividad.');
 if(result._episode_id)return {review:null,episode:validateRepairTransition(goal,result,prepared)};
 let event=prepared.event,review=null;if(phase==='REVIEW'){if(!Array.isArray(goal.reviews))throw policyError('INVALID_REVIEW','No existe el estado de repaso requerido.');review=goal.reviews.find(x=>x&&x.id===id);if(!review||!review.question||typeof review.question!=='object'||!String(review.question.prompt||'').trim()||!Array.isArray(review.history))throw policyError('INVALID_REVIEW','No existe un repaso válido para este resultado.')}
 if(isLearningFailure(event)&&phase!=='DIAGNOSTIC'&&phase!=='REVIEW'){let l=goal.lessons&&goal.lessons[id],q=l&&(phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:phase==='INTEGRATE'?l.integration:l.independent);if(!q||typeof q!=='object')throw policyError('INVALID_ACTIVITY_REFERENCE','No existe la actividad original necesaria para intervenir.')}
 return {review}
}
function commitTransition(goal,id,phase,answer,result,event,validated){
 let s=goal.session,st=state(goal,id);s.hints=0;st.confidence=verified(goal,id)?'verified':'unverified';
 if(validated.episode){let episode=transitionRepairEpisode(goal,validated.episode,event);st.confidence=verified(goal,id)?'verified':'unverified';save();render();return Boolean(episode)}
 if(phase==='REVIEW'){let r=validated.review,was=r.question;r.history.push({at:Date.now(),prompt:was.prompt,pass:event.result==='CORRECT',attempt_id:event.attempt_id});r.step=event.result==='CORRECT'?Math.min(INTERVALS.length-1,r.step+1):0;r.due=Date.now()+INTERVALS[r.step]*DAY;r.question=null;s.mode='DIAGNOSTIC';save();if(event.result!=='CORRECT')startTeach(goal,id);else{page='dashboard';render()}return true}
 if(phase==='DIAGNOSTIC'){if(event.result==='CORRECT'){st.level=Math.max(st.level,3);s.mode='CHALLENGE';save();render()}else startTeach(goal,id);return true}
 if(event.result==='UNKNOWN'){save();note('No se pudo determinar el resultado; el intento quedó registrado sin penalización.',true);render();return true}
 if(isLearningFailure(event)){let decision=nextIntervention(goal,id,phase,{...result,status:event.result});goal.events.push({type:'TUTOR_DECISION',at:Date.now(),id,phase,decision,error:event.error_type||'none',attempt_id:event.attempt_id});save();openIntervention(goal,id,phase,answer,{...result,status:event.result},event);return true}
 s.tries=0;if(phase==='CHALLENGE'){st.level=5;s.mode='INTEGRATE'}else if(phase==='COMPREHENSION'){st.level=Math.max(st.level,3);s.mode='GUIDED'}else if(phase==='GUIDED'){st.level=Math.max(st.level,4);s.mode='INDEPENDENT'}else if(phase==='INDEPENDENT'){st.level=Math.max(st.level,5);s.mode='INTEGRATE'}else if(phase==='INTEGRATE'){st.level=6;st.confidence=verified(goal,id)?'verified':'unverified';schedule(goal,id);nextAfterLesson(goal);return true}save();render();return true
}
function applyResult(goal,id,phase,answer,result){if(!result||typeof result!=='object'||!result._activity||!result._attempt_id)throw policyError('INVALID_RESULT','El resultado está incompleto y no puede aplicarse.');let activity=result._activity,attemptId=result._attempt_id,help=result._episode_id?Math.max(0,Number(result._help_used)||0):Number(goal?.session?.hints)||0,prepared=prepareRecord(goal,id,phase,answer,result,help,activity,attemptId),validated=validateTransition(goal,id,phase,result,prepared),event=commitRecord(goal,id,prepared);return commitTransition(goal,id,phase,answer,result,event,validated)}
function applyManualCorrection(goal,id,phase,answer,assessment,correctedStatus,correctionId=newId('attempt')){
 if(!assessment||typeof assessment!=='object'||!assessment._activity||!assessment._attempt_id)throw policyError('INVALID_RESULT','La evaluación original está incompleta.');let activity=assessment._activity,originalAttempt=assessment._attempt_id,contract=normalizeActivityContract(activity),disposition=attemptDisposition(goal,originalAttempt,contract,id);if(disposition==='collision')throw policyError('ATTEMPT_COLLISION','El intento original pertenece a otro nodo o actividad.');
 let expected={DIAGNOSTIC:'DIAGNOSTIC',COMPREHENSION:'COMPREHENSION',GUIDED:'GUIDED',INDEPENDENT:'INDEPENDENT',CHALLENGE:'INDEPENDENT',INTEGRATE:'INTEGRATE',REVIEW:'REVIEW'}[phase];if(!expected||contract.stage!==expected)throw policyError('INVALID_PHASE','La fase no corresponde al contrato de la actividad.');
 let prior=Array.isArray(goal?.events)?goal.events.find(x=>x&&x.type==='EVIDENCE'&&x.attempt_id===originalAttempt):null,originalPrepared=null;if(!prior)originalPrepared=prepareRecord(goal,id,phase,answer,{...assessment,_audit_only:true,_actor:'evaluator',_source:'evaluation',_decision:'superseded'},Number(goal?.session?.hints)||0,activity,originalAttempt);
 let originalEvent=prior||originalPrepared.event,corrected={...assessment,status:resultStatus(correctedStatus),_attempt_id:correctionId,_corrected:true,_original_status:originalEvent.result??assessment.status,_correction_of:originalEvent.evidence_id,_original_attempt_id:originalAttempt,_actor:'user',_source:'manual_correction',_decision:'corrected'},correctedPrepared=prepareRecord(goal,id,phase,answer,corrected,Number(goal?.session?.hints)||0,activity,correctionId),validated=prior?null:validateTransition(goal,id,phase,corrected,correctedPrepared);
 if(originalPrepared)commitRecord(goal,id,originalPrepared);let event=commitRecord(goal,id,correctedPrepared);if(prior){let st=state(goal,id);st.confidence=verified(goal,id)?'verified':'unverified';save();return true}return commitTransition(goal,id,phase,answer,corrected,event,validated)
}
async function reviewView(box,goal,n){let r=goal.reviews.find(x=>x.id===n.id);if(!r){goal.session.mode='DIAGNOSTIC';render();return}if(!r.question){try{let d=await api('/api/review',{goal:goal.goal,concept:n.name,level:r.step,previous:r.history.slice(-3).map(x=>x.prompt).join('; ')});r.question=d.question;save()}catch(e){note(e.message+' Reutilizaré un caso guardado.',true);r.question=goal.lessons[n.id]?.independent||n.probe;save()}}renderQuestion(box,r.question,n.id,'REVIEW','spaced_review');box.append(B('No recuerdo; volvamos a aprenderlo',()=>{r.due=Date.now()+DAY;r.step=0;r.question=null;save();startTeach(goal,n.id)},true))}


// Context stack: the top context alone is evaluated. Parents remain paused.
function repairCanRequestHint(stage){return ['CHECK','GUIDED','INDEPENDENT'].includes(stage)}
function registerRepairHint(episode,stage,source='requested'){if(!episode||episode.closed_at||!repairCanRequestHint(stage))return false;episode.current_help_used=Math.max(0,Number(episode.current_help_used)||0)+1;episode.hint_history=Array.isArray(episode.hint_history)?episode.hint_history:[];episode.hint_history.push({stage,source,at:Date.now()});return true}
function contextStack(goal){if(!Array.isArray(goal.contextStack))goal.contextStack=[];return goal.contextStack}
function topContext(goal){let s=contextStack(goal);return s[s.length-1]}
function canPushContext(goal,ctx){let stack=contextStack(goal);if(stack.length>=REPAIR_LIMITS.max_depth)return {ok:false,reason:'MAX_DEPTH'};if(ctx?.episode_id&&ctx?.gap_id&&stack.some(x=>x.episode_id===ctx.episode_id&&x.gap_id===ctx.gap_id))return {ok:false,reason:'DUPLICATE_GAP'};return {ok:true,reason:null}}
function pushContext(goal,ctx){let allowed=canPushContext(goal,ctx);if(!allowed.ok){let episode=ctx?.episode_id?repairEpisode(goal,ctx.episode_id):null,reason=allowed.reason==='MAX_DEPTH'?'Se alcanzó la profundidad máxima de cuatro contextos.':'La misma laguna ya está abierta en este episodio.';if(episode&&!episode.closed_at)closeRepairEpisode(goal,episode,'PARTIAL',reason);throw policyError(allowed.reason,reason)}let s=contextStack(goal),parent=topContext(goal),copy={...(ctx||{}),history:Array.isArray(ctx?.history)?ctx.history.map(x=>({...x})):[]};if(parent){parent.status='PAUSED';copy.parent_context_id=parent.context_id}copy.status='ACTIVE';s.push(copy);goal.session.mode='CONTEXT';save();return copy}
function popContext(goal,outcome='PARTIAL',reason=null){let s=contextStack(goal),child=s.pop(),episode=child?.episode_id?repairEpisode(goal,child.episode_id):null,at=Date.now();goal.events=Array.isArray(goal.events)?goal.events:[];if(child){child.status=String(outcome);child.closed_at=at;child.close_reason=reason||null;if(episode){episode.context_history.push(cloneData(child,{}));goal.events.push({type:'REPAIR_CONTEXT_CLOSED',episode_id:episode.episode_id,context_id:child.context_id,status:String(outcome),reason:reason||null,at})}else goal.events.push({type:'CONTEXT_RECOVERY',context_id:child.context_id||null,status:String(outcome),reason:reason||'Contexto sin episodio auditable.',at})}let parent=topContext(goal);if(episode&&!parent&&!episode.closed_at){let terminal=['PARTIAL','FAILED','ABANDONED'].includes(String(outcome))?String(outcome):'PARTIAL';episode.status=terminal;episode.closed_at=at;episode.close_reason=reason||'El contexto raíz se cerró sin un resultado final del episodio.';goal.events.push({type:'REPAIR_EPISODE_CLOSED',episode_id:episode.episode_id,status:terminal,reason:episode.close_reason,source:'pop_context',at})}if(parent){parent.status='RETURNING';parent.history=parent.history||[];parent.history.push({child:child?.context_id,status:String(outcome),reason:reason||null});goal.session.mode='CONTEXT'}else if(episode){let snapshot=episode.parent_context_snapshot||{};goal.session.mode=snapshot.mode||'DIAGNOSTIC';goal.session.node=snapshot.node||episode.parent_node_id||null;goal.session.stack=Array.isArray(snapshot.stack)?[...snapshot.stack]:[];goal.session.stage=snapshot.stage||goal.session.stage;goal.session.tries=Number.isFinite(snapshot.tries)?snapshot.tries:0}else goal.session.mode=child?.resume_mode||'DIAGNOSTIC';save();return child}
function contextScreen(box,goal){
 let ctx=topContext(goal);if(!ctx){goal.events=Array.isArray(goal.events)?goal.events:[];goal.events.push({type:'CONTEXT_RECOVERY',context_id:null,status:'ABANDONED',reason:'La sesión indicaba CONTEXT sin un contexto activo.',at:Date.now()});goal.session.mode='DIAGNOSTIC';save();render();return}let episode=repairEpisode(goal,ctx.episode_id);if(!episode){popContext(goal,'ABANDONED','El contexto legacy no tenía un episodio auditable.');render();return}let current=episodeActivity(episode);if(!current){if(!episode.closed_at)closeRepairEpisode(goal,episode,'PARTIAL','No existe una actividad válida para la etapa actual.');render();return}
 let labels={DIAGNOSTIC:'Diagnóstico breve',CHECK:'Comprobación del prerrequisito',GUIDED:'Práctica guiada',INDEPENDENT:'Intento independiente',PARENT_RETEST:'Reintento del problema padre',TRANSFER_CHECK:'Variante de transferencia'};
 box.append(E('p',`Episodio ${episode.episode_id} · ${episode.status}`),E('p',`Problema padre: ${episode.parent_question?.prompt||'sin texto'}`));if(episode.selected_gap)box.append(E('p',`Laguna prioritaria: ${episode.selected_gap.concept} (${episode.selected_gap.status})`));box.append(E('h3',labels[current.phase]||current.phase),E('p',current.question.prompt));
 let ans=E('textarea'),feedback=E('div'),attemptId=newId('attempt'),submitted=false;ans.placeholder='Explica tu razonamiento.';box.append(ans);
 function hint(){if(submitted)return;if(registerRepairHint(episode,current.phase,'requested')){feedback.append(E('p','Pista registrada: vuelve al principio, identifica el dato relevante y explica el siguiente paso.'));save()}}
 let button=B('Evaluar esta etapa',()=>task('Evaluando el episodio…',async()=>{if(submitted)return;let text=ans.value.trim();if(!text)throw Error('Escribe una respuesta.');submitted=true;button.disabled=true;ans.disabled=true;let r;try{r=await api('/api/context/step',{context:{context_id:ctx.context_id,episode_id:episode.episode_id,status:'ACTIVE',question:current.question,stage:current.phase},answer:text})}catch(error){submitted=false;button.disabled=false;ans.disabled=false;throw error}feedback.replaceChildren(E('p',r.feedback||''));if(r.hint)feedback.append(E('p',`Pista del evaluador: ${r.hint}`));let applied=false,continueButton=B('Continuar',()=>{if(applied)return false;let priorStage=current.phase,ok=applyResult(goal,episode.parent_node_id,current.activity.stage,text,{...r,_activity:current.activity,_attempt_id:attemptId,_episode_id:episode.episode_id,_repair_stage:current.phase,_help_used:episode.current_help_used});if(ok){applied=true;continueButton.disabled=true;if(String(r.hint||'').trim()&&!episode.closed_at&&episode.stage===priorStage){registerRepairHint(episode,priorStage,'evaluator_feedback');save()}}return ok});feedback.append(continueButton)}));box.append(button);if(repairCanRequestHint(current.phase))box.append(B('Dame una pista',hint,true));box.append(B('Abandonar episodio',()=>{if(submitted)return;closeRepairEpisode(goal,episode,'ABANDONED','El usuario abandonó el episodio.');render()},true),feedback)
}
function render(){note('');if(page==='home')home();else if(page==='dashboard')dashboard();else if(g()?.session?.mode==='CONTEXT'){app.replaceChildren();nav();let box=block(g().goal);contextScreen(box,g())}else session()}
function setStoreForTests(value){store=value;page='session';return store}
if(typeof module!=='undefined'&&module.exports){module.exports={normalizeImportedStore,normalizeGoal,normalizeActivityContract,activityContract,evidenceTargets,activityEvidence,sufficient,deriveCoverage,updateCoverage,attemptDisposition,wasAttemptApplied,prepareRecord,record,verified,nextNode,masteredCount,progressDiscrepancy,derivedStartMode,startTeach,renderQuestion,applyResult,applyManualCorrection,normalizeRepairEpisode,prepareRepairPlan,createRepairEpisode,repairEpisode,repairEpisodes,episodeActivity,closeRepairEpisode,repairQuestionFingerprint,repairActivityRelation,equivalentRepairActivity,repairCanRequestHint,registerRepairHint,contextStack,canPushContext,pushContext,popContext,contextScreen,setStoreForTests,EVIDENCE_POLICY_VERSION,REPAIR_POLICY_VERSION,REPAIR_LIMITS}}else render();
