
'use strict';
const KEY='ruta-adaptativa-v4', app=document.getElementById('app'),statusEl=document.getElementById('status');
const INTERVALS=[1,3,7,14,30,60,90], DAY=86400000;
let store;try{store=JSON.parse(localStorage.getItem(KEY))}catch{};if(!store||!Array.isArray(store.goals))store={goals:[],active:null};
let page='home',busy=false;
const E=(t,s)=>{let e=document.createElement(t);if(s!==undefined)e.textContent=s;return e};
const B=(s,f,alt=false)=>{let b=E('button',s);b.type='button';if(alt)b.className='quiet';b.onclick=f;return b};
const block=s=>{let x=E('section');x.className='box';x.append(E('h2',s));app.append(x);return x};
const g=()=>store.goals.find(x=>x.id===store.active);
function save(){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{note('El navegador no pudo guardar el progreso.',true)}}
function note(s,bad=false){statusEl.textContent=s;statusEl.className=bad?'err':'ok'}
async function api(route,payload){let c=new AbortController(),timer=setTimeout(()=>c.abort(),100000);try{let r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:c.signal});let d=await r.json();if(!r.ok)throw Error(d.error||'Error del servidor');return d}catch(e){if(e.name==='AbortError')throw Error('La solicitud tardó demasiado; revisa el servidor antes de repetir.');if(e instanceof TypeError)throw Error('No se pudo contactar al servidor local.');throw e}finally{clearTimeout(timer)}}
async function task(label,fn){if(busy)return;busy=true;note(label);try{await fn();if(statusEl.textContent===label)note('Listo.')}catch(e){note(e?.message||String(e),true);console.error(e)}finally{busy=false}}
function nav(){app.append(B('Mis metas',()=>{page='home';render()},true));if(g())app.append(B('Mi ruta',()=>{page='dashboard';render()},true))}
function backup(){let url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'})),a=E('a');a.href=url;a.download='ruta-v4-respaldo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function home(){app.replaceChildren();let b=block('Una meta, no un curso genérico'),name=E('input'),context=E('textarea');name.placeholder='Ej. Entender el tratamiento superficial';context.placeholder='Opcional: experiencia previa, sin información interna';b.append(name,context,B('Empezar ruta',()=>task('Construyendo solo el mapa inicial…',async()=>{if(name.value.trim().length<5)throw Error('Escribe una meta más concreta.');let d=await api('/api/map',{goal:name.value.trim(),context:context.value.trim()});let goal={id:crypto.randomUUID(),goal:name.value.trim(),context:context.value.trim(),nodes:d.nodes,coverage:Array.isArray(d.coverage)?d.coverage:[],map_version:d.map_version||1,map_updates:[],learner:{},lessons:{},reviews:[],events:[],session:{mode:'DIAGNOSTIC',node:null,stack:[],stage:'teach',tries:0}};store.goals.push(goal);store.active=goal.id;save();page='session';render()})));
if(store.goals.length){let list=block('Mis metas');for(let x of store.goals)list.append(B(x.goal,()=>{store.active=x.id;page='dashboard';render()}),B('Eliminar',()=>{if(confirm('¿Eliminar esta meta y sus avances?')){store.goals=store.goals.filter(z=>z.id!==x.id);if(store.active===x.id)store.active=null;save();render()}},true),E('br'))}app.append(B('Exportar respaldo',backup,true));let input=E('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{let d=JSON.parse(await input.files[0].text());if(!Array.isArray(d.goals)||!d.goals.every(x=>x.id&&Array.isArray(x.nodes)&&x.learner&&x.session))throw Error('Este archivo no es un respaldo de Ruta v4.');if(!confirm('¿Reemplazar los datos v4 de este navegador por el respaldo?'))return;store=d;save();render()}catch(e){note(e.message,true)}};app.append(E('p','Restaurar respaldo v4 (reemplaza los datos actuales):'),input)}
function coverageOf(goal,id){goal.coverage=Array.isArray(goal.coverage)?goal.coverage:[];let c=goal.coverage.find(x=>x.id===id);if(!c){let n=goal.nodes.find(x=>x.id===id)||{name:id,kind:'concept',prerequisites:[]};c={id,name:n.name,kind:n.kind,priority:'important',prerequisites:n.prerequisites||[],contexts:[],status:'UNKNOWN',confidence:0,last_evidence:null,dimensions:[{id:'conceptual',name:'Comprensión',required:true,status:'UNKNOWN',evidence:[]},{id:'direct_application',name:'Aplicación',required:true,status:'UNKNOWN',evidence:[]}],updates:[]};goal.coverage.push(c)}c.dimensions=Array.isArray(c.dimensions)?c.dimensions:[];return c}
function state(goal,id){if(!goal.learner[id])goal.learner[id]={level:0,confidence:'unverified',evidence:[],errors:[],last:null};let s=goal.learner[id];s.evidence=Array.isArray(s.evidence)?s.evidence:[];s.errors=Array.isArray(s.errors)?s.errors:[];coverageOf(goal,id);return s}
function evidenceTargets(phase,error){if(error==='algebra'||error==='arithmetic')return ['equation_manipulation'];if(error==='units')return ['units'];if(error==='formula_selection')return ['method_selection'];if(error==='variable_identification')return ['variables'];if(error==='interpretation')return ['interpretation'];if(error==='transfer')return ['transfer'];if(phase==='INTEGRATE')return ['transfer','interpretation'];if(phase==='REVIEW')return ['memory'];if(phase==='GUIDED')return ['direct_application'];if(phase==='INDEPENDENT')return ['direct_application'];return ['conceptual']}
function activityEvidence(phase,assessment,help){return {at:Date.now(),phase,status:assessment.status,error:assessment.error_type||'none',help:help||0,independent:phase==='INDEPENDENT'||phase==='INTEGRATE'||phase==='REVIEW',varied:phase==='INTEGRATE'||phase==='REVIEW'}}
function sufficient(d){let e=Array.isArray(d.evidence)?d.evidence:[],ok=e.filter(x=>x.status==='CORRECT');if(!ok.length)return false;if(d.id==='direct_application'||d.id==='procedure')return ok.some(x=>x.independent);if(d.id==='transfer')return ok.some(x=>x.independent&&x.varied);if(d.id==='memory')return ok.some(x=>x.phase==='REVIEW');return true}
function updateCoverage(goal,id,phase,assessment,help=0){let c=coverageOf(goal,id),targets=evidenceTargets(phase,assessment.error_type||'none');for(let k of targets){let d=c.dimensions.find(x=>x.id===k);if(!d)continue;d.evidence=Array.isArray(d.evidence)?d.evidence:[];d.evidence.push(activityEvidence(phase,assessment,help));d.evidence=d.evidence.slice(-8);d.status=sufficient(d)?'MASTERED':assessment.status==='PARTIAL'?'PARTIALLY_UNDERSTOOD':'LEARNING'}let req=c.dimensions.filter(d=>d.required),done=req.filter(sufficient).length;c.confidence=req.length?done/req.length:0;c.last_evidence=Date.now();c.status=done===req.length&&req.length?'MASTERED':done?'PARTIALLY_UNDERSTOOD':'LEARNING'}
function nextIntervention(goal,id,phase,result){let e=result?.error_type||'none',c=coverageOf(goal,id);if(result?.status==='CORRECT')return phase==='INTEGRATE'?'SPACED_REVIEW':'ADVANCE';if(e==='prerequisite')return 'PREREQUISITE';if(['algebra','arithmetic','units','formula_selection','variable_identification'].includes(e))return 'TARGETED_MICRO';if(e==='conceptual')return 'EXPLAIN_THEN_MICRO';if(e==='memory')return 'RETRIEVAL_REPAIR';if(e==='transfer'||e==='application')return 'CONTEXTUAL_PRACTICE';return c.status==='LEARNING'?'GUIDED_REPAIR':'TARGETED_MICRO'}
function originalQuestion(goal,id,phase){let l=goal.lessons[id];return phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:phase==='INTEGRATE'?l.integration:l.independent}
function openIntervention(goal,id,phase,answer,result){let decision=nextIntervention(goal,id,phase,result),q=originalQuestion(goal,id,phase);goal.events.push({at:Date.now(),id,phase,decision,error:result.error_type||'none'});task('Preparando una intervención específica…',async()=>{let ctx=await api('/api/context/create',{question:q,answer,feedback:result.feedback});ctx.parent_context_id=null;ctx.parent_question=q;ctx.resume_mode=phase;ctx.decision=decision;ctx.origin_node=id;pushContext(goal,ctx);render()})}
const verified=(goal,id)=>{let s=state(goal,id),c=coverageOf(goal,id);return s.level>=3&&s.confidence==='verified'&&c.status==='MASTERED'};
function relevant(goal){let nodes=goal.nodes,byId=Object.fromEntries(nodes.map(n=>[n.id,n]));let out=[];let open=new Set(nodes.map(n=>n.id));while(open.size){let ready=nodes.filter(n=>open.has(n.id)&&n.prerequisites.every(d=>!open.has(d)||!byId[d]));if(!ready.length)break;ready.sort((a,b)=>a.level-b.level);for(let n of ready){out.push(n);open.delete(n.id)}}return out}
function nextNode(goal){return relevant(goal).find(n=>state(goal,n.id).level<6)||null}
function nextLearningAction(goal){let s=goal.session;if(s.mode==='TEACH')return 'EXPLAIN';if(s.mode==='COMPREHENSION')return 'CHECK';if(s.mode==='GUIDED')return 'GUIDED_PRACTICE';if(s.mode==='INDEPENDENT')return 'INDEPENDENT_PRACTICE';if(s.mode==='INTEGRATE')return 'INTEGRATE_WITH_GOAL';if(s.mode==='REVIEW')return 'SPACED_REVIEW';return 'PROBE_PREREQUISITE'}
function record(goal,id,phase,answer,assessment,help=0){let s=state(goal,id);updateCoverage(goal,id,phase,assessment,help);s.last=Date.now();s.evidence.push({at:s.last,phase,answer:answer.slice(0,700),status:assessment.status,hints:help,error:assessment.error_type||'none'});s.evidence=s.evidence.slice(-30);if(assessment.status!=='CORRECT')s.errors.push({at:s.last,type:assessment.error_type||'unknown',phase});s.errors=s.errors.slice(-20);goal.events.push({at:s.last,id,phase,status:assessment.status});goal.events=goal.events.slice(-200);save()}
function prerequisite(goal,id,visited=new Set()){if(visited.has(id))return null;visited.add(id);let n=goal.nodes.find(n=>n.id===id);if(!n)return null;for(let dep of n.prerequisites){let prior=prerequisite(goal,dep,visited);if(prior)return prior;if(!verified(goal,dep))return dep}return null}
function startTeach(goal,id){let s=goal.session,dep=prerequisite(goal,id);if(dep&&dep!==id){if(!s.stack.includes(id))s.stack.push(id);id=dep}let known=state(goal,id);s.node=id;s.mode=known.level===0?'TEACH':'COMPREHENSION';s.stage='teach';s.tries=0;save();page='session';render()}
function nextAfterLesson(goal){let s=goal.session,prev=s.stack.pop();s.node=null;s.tries=0;if(prev&&!verified(goal,prev)){startTeach(goal,prev);return}s.mode='DIAGNOSTIC';save();render()}
function schedule(goal,id){if(!goal.reviews.some(x=>x.id===id))goal.reviews.push({id,due:Date.now()+DAY,step:0,question:null,history:[]});save()}
function dashboard(){let goal=g();if(!goal){page='home';render();return}app.replaceChildren();nav();let b=block(goal.goal),due=goal.reviews.filter(r=>r.due<=Date.now());b.append(E('p',`Hoy: ${due.length} repasos · ${goal.nodes.filter(n=>state(goal,n.id).level>=5).length} habilidades demostradas · ${goal.nodes.length} en el mapa.`),B('Seguir aprendiendo',()=>{page='session';render()}),B(`Repasar (${due.length})`,()=>{if(!due.length){note('Aún no hay repasos pendientes.');return}goal.session.mode='REVIEW';goal.session.node=due[0].id;save();page='session';render()}));let list=block('Cobertura del objetivo');for(let n of relevant(goal)){let s=state(goal,n.id),c=coverageOf(goal,n.id);list.append(E('p',`${c.status==='MASTERED'?'✓':s.level?'→':'○'} ${n.name} · ${c.status} · ${c.dimensions.filter(d=>d.required).map(d=>d.id+':'+d.status).join(', ')} · ${n.outcome}`))}app.append(B('Guardar respaldo',backup,true))}
async function session(){let goal=g();if(!goal){page='home';render();return}let s=goal.session;app.replaceChildren();nav();let b=block(goal.goal),action=nextLearningAction(goal);
if(s.mode==='DIAGNOSTIC'){let n=nextNode(goal);if(!n){b.append(E('p','Por ahora recorrimos esta ruta. Puedes practicar y revisar conceptos después.'));return}s.node=n.id;save();let p=b.appendChild(E('p',`Antes de avanzar, veamos si ya conoces «${n.name}». Si nunca lo has visto, te lo enseño.`));renderQuestion(b,n.probe,n.id,'DIAGNOSTIC');b.append(B('No sé; enséñamelo',()=>{record(goal,n.id,'DIAGNOSTIC','No sé',{status:'UNKNOWN',error_type:'lack_of_exposure'});startTeach(goal,n.id)},true));return}
let n=goal.nodes.find(x=>x.id===s.node);if(!n){s.mode='DIAGNOSTIC';render();return}let coverage=coverageOf(goal,n.id);b.append(E('p',`Ahora: ${n.name} · ${action}`),E('p',`Cobertura: ${coverage.status} · ${coverage.dimensions.filter(d=>d.required).map(d=>d.name+'='+d.status).join(', ')}`));if(s.mode==='REVIEW'){await reviewView(b,goal,n);return}
if(!goal.lessons[n.id]){b.append(E('p','Preparando solo esta microlección…'));await task('Preparando una explicación breve…',async()=>{let parent=s.stack[s.stack.length-1],p=goal.nodes.find(x=>x.id===parent);goal.lessons[n.id]=await api('/api/lesson',{goal:goal.goal,name:n.name,parent:p?.name||goal.goal});save();render()});return}
let l=goal.lessons[n.id];
if(s.mode==='TEACH'){b.append(E('h3','Una idea a la vez'),E('p',l.explanation),E('p','Ejemplo'),E('pre',l.example),E('p',`Error habitual: ${l.common_error}`));b.append(B('Ahora lo intento',()=>{s.mode='COMPREHENSION';state(goal,n.id).level=Math.max(1,state(goal,n.id).level);save();render()}));return}
let phase=s.mode,question=phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:(phase==='INDEPENDENT'||phase==='CHALLENGE')?l.independent:l.integration;
renderQuestion(b,question,n.id,phase);
if(phase==='GUIDED')b.append(B('Dame una pista',()=>{let x=E('p',`Pista: ${l.common_error} Piensa qué dato falta para decidir.`);b.append(x);s.hints=(s.hints||0)+1;save()},true));
if(phase==='COMPREHENSION')b.append(B('No lo entendí; vuelve al ejemplo',()=>{s.mode='TEACH';save();render()},true));
}
function renderQuestion(box,question,id,phase){
 let goal=g(),answer=E('textarea'),feedback=E('div');box.append(E('h3',question.prompt));
 answer.placeholder='Tu idea y por qué. No hace falta que sea perfecta.';
 let submit=B('Compartir mi intento',()=>task('Analizando tu razonamiento…',async()=>{
  let text=answer.value.trim();if(!text)throw Error('Escribe una idea o elige «No sé».');
  let assessment=await api('/api/evaluate',{question,answer:text,phase});answer.disabled=true;
  feedback.replaceChildren(E('p',assessment.feedback));
  if(assessment.hint)feedback.append(E('p',`Pista: ${assessment.hint}`));
  feedback.append(B('Continuar',()=>applyResult(goal,id,phase,text,assessment)));
  feedback.append(B('Corregir evaluación',()=>{let ok=confirm('¿Tu respuesta demuestra comprensión?');applyResult(goal,id,phase,text,{...assessment,status:ok?'CORRECT':'PARTIAL'})},true));
 }));box.append(answer,submit,feedback)
}
function applyResult(goal,id,phase,answer,result){let s=goal.session,st=state(goal,id);record(goal,id,phase,answer,result,s.hints||0);s.hints=0;if(phase==='DIAGNOSTIC'){if(result.status==='CORRECT'){st.level=Math.max(st.level,3);st.confidence='verified';s.mode='CHALLENGE';save();render()}else startTeach(goal,id);return}
if(result.status!=='CORRECT'){let decision=nextIntervention(goal,id,phase,result);goal.events.push({at:Date.now(),id,phase,decision,error:result.error_type||'none'});if(phase==='CHALLENGE'){startTeach(goal,id);return}s.tries++;if(result.status==='MISCONCEPTION'&&s.tries>=2)s.mode='TEACH';else if(phase==='INDEPENDENT')s.mode='GUIDED';else if(s.tries>=2)s.mode='TEACH';save();render();return}
s.tries=0;if(phase==='CHALLENGE'){st.level=5;s.mode='INTEGRATE'}else if(phase==='COMPREHENSION'){st.level=Math.max(st.level,3);s.mode='GUIDED'}else if(phase==='GUIDED'){st.level=Math.max(st.level,4);s.mode='INDEPENDENT'}else if(phase==='INDEPENDENT'){st.level=Math.max(st.level,5);s.mode='INTEGRATE'}else if(phase==='INTEGRATE'){st.level=6;st.confidence='verified';schedule(goal,id);nextAfterLesson(goal);return}else if(phase==='REVIEW'){s.mode='DIAGNOSTIC'}save();render()}
async function reviewView(box,goal,n){let r=goal.reviews.find(x=>x.id===n.id);if(!r){goal.session.mode='DIAGNOSTIC';render();return}if(!r.question){try{let d=await api('/api/review',{goal:goal.goal,concept:n.name,level:r.step,previous:r.history.slice(-3).map(x=>x.prompt).join('; ')});r.question=d.question;save()}catch(e){note(e.message+' Reutilizaré un caso guardado.',true);r.question=goal.lessons[n.id]?.independent||n.probe;save()}}renderQuestion(box,r.question,n.id,'REVIEW');box.append(B('No recuerdo; volvamos a aprenderlo',()=>{r.due=Date.now()+DAY;r.step=0;r.question=null;save();startTeach(goal,n.id)},true))}
const originalApply=applyResult;
applyResult=function(goal,id,phase,answer,result){if(phase!=='REVIEW')return originalApply(goal,id,phase,answer,result);record(goal,id,phase,answer,result);let r=goal.reviews.find(x=>x.id===id);let was=r.question;r.history.push({at:Date.now(),prompt:was.prompt,pass:result.status==='CORRECT'});r.history=r.history.slice(-20);r.step=result.status==='CORRECT'?Math.min(INTERVALS.length-1,r.step+1):0;r.due=Date.now()+INTERVALS[r.step]*DAY;r.question=null;goal.session.mode='DIAGNOSTIC';save();if(result.status!=='CORRECT'){startTeach(goal,id)}else{page='dashboard';render()}};


// Context stack: the top context alone is evaluated. Parents remain paused.
function contextStack(goal){if(!Array.isArray(goal.contextStack))goal.contextStack=[];return goal.contextStack}
function topContext(goal){let s=contextStack(goal);return s[s.length-1]}
function pushContext(goal,ctx){let s=contextStack(goal),parent=topContext(goal);if(parent){parent.status='PAUSED';ctx.parent_context_id=parent.context_id}ctx.status='ACTIVE';s.push(ctx);goal.session.mode='CONTEXT';save()}
function popContext(goal,mastery){let s=contextStack(goal),child=s.pop();if(child)child.status='MASTERED';let parent=topContext(goal);if(parent){parent.status='RETURNING';parent.history=parent.history||[];parent.history.push({child:child.context_id,mastery});goal.session.mode='CONTEXT'}else{goal.session.mode=child?.resume_mode||'DIAGNOSTIC'}save()}
const oldApplyForContexts=applyResult;
applyResult=function(goal,id,phase,answer,result){
 if(phase==='REVIEW'||phase==='DIAGNOSTIC'||result.status==='CORRECT')return oldApplyForContexts(goal,id,phase,answer,result);
 record(goal,id,phase,answer,result,goal.session.hints||0);goal.session.hints=0;
 openIntervention(goal,id,phase,answer,result);
};
function contextScreen(box,goal){
 let ctx=topContext(goal);if(!ctx){goal.session.mode='DIAGNOSTIC';save();render();return}
 ctx.history=Array.isArray(ctx.history)?ctx.history:[];ctx.attempts=Number.isFinite(ctx.attempts)?ctx.attempts:0;ctx.stage=ctx.stage||'CHECK';
 box.append(E('p',`Contexto activo: ${ctx.concept} · intervención: ${ctx.decision||'MICRO_TUTOR'}`),E('p',`Objetivo: ${ctx.objective}`));
 if(ctx.stage==='CHECK'){if(ctx.explanation)box.append(E('p',ctx.explanation));if(ctx.example)box.append(E('p',`Ejemplo trabajado: ${ctx.example}`))}
 let labels={CHECK:'Comprobación breve',GUIDED:'Práctica guiada: explica cada paso; usa la pista si la necesitas.',INDEPENDENT:'Práctica independiente: aplícalo en una respuesta completa.'};
 box.append(E('h3',labels[ctx.stage]||'Práctica'),E('p',ctx.question.prompt));
 let ans=E('textarea'),feedback=E('div');ans.placeholder='Explica tu razonamiento. Si necesitas ayuda, usa la pista.';box.append(ans);
 function hint(){let text=ctx.example||'Vuelve al principio y nombra el paso que conecta los datos con la respuesta.';feedback.append(E('p',`Pista: ${text}`));ctx.hints_used=(ctx.hints_used||0)+1;save()}
 function retry(){ctx.status='ACTIVE';save();render()}
 function advance(){if(ctx.stage==='CHECK'){ctx.stage='GUIDED';ctx.status='ACTIVE';save();render();return}if(ctx.stage==='GUIDED'){ctx.stage='INDEPENDENT';ctx.status='ACTIVE';save();render();return}ctx.status='MASTERED';ctx.mastery=(ctx.mastery||0)+1;save();popContext(goal,ctx.mastery);render()}
 let button=B('Evaluar esta práctica',()=>task('Evaluando la intervención…',async()=>{let text=ans.value.trim();if(!text)throw Error('Escribe una respuesta.');let r=await api('/api/context/step',{context:{...ctx,status:'ACTIVE'},answer:text});ctx.attempts++;ctx.history.push({stage:ctx.stage,question:ctx.question.prompt,answer:text,result:r,hints:ctx.hints_used||0});ans.disabled=true;button.disabled=true;feedback.replaceChildren(E('p',r.feedback||''));if(r.hint)feedback.append(E('p',`Pista: ${r.hint}`));if(r.status==='CORRECT'){feedback.append(B(ctx.stage==='INDEPENDENT'?'Volver al problema original':'Continuar',advance));}else{ctx.status='NEEDS_DECOMPOSITION';if((ctx.hints_used||0)===0)feedback.append(B('Dame una pista',hint,true));feedback.append(B('Intentar otra vez esta práctica',retry,true));if(contextStack(goal).length<4)feedback.append(B('Zoom: aislar un prerrequisito',()=>task('Creando contexto hijo…',async()=>{let child=await api('/api/context/zoom',{context:ctx,answer:text,feedback:r.feedback});pushContext(goal,child);render()})));save()}}));box.append(button);if(ctx.stage==='GUIDED')box.append(B('Dame una pista',hint,true));box.append(feedback)
}
function render(){note('');if(page==='home')home();else if(page==='dashboard')dashboard();else if(g()?.session?.mode==='CONTEXT'){app.replaceChildren();nav();let box=block(g().goal);contextScreen(box,g())}else session()}
render();
