
'use strict';
const KEY='ruta-adaptativa-v4', app=document.getElementById('app'),statusEl=document.getElementById('status');
const INTERVALS=[1,3,7,14,30,60,90], DAY=86400000;
let store;try{store=JSON.parse(localStorage.getItem(KEY))}catch{};if(!store||!Array.isArray(store.goals))store={goals:[],active:null};
let page='home',busy=false;
const E=(t,s)=>{let e=document.createElement(t);if(s!==undefined)e.textContent=s;return e};
const B=(s,f,alt=false)=>{let b=E('button',s);b.type='button';if(alt)b.className='quiet';b.onclick=f;return b};
const block=s=>{let x=E('section');x.className='box';x.append(E('h2',s));app.append(x);return x};
const g=()=>store.goals.find(x=>x.id===store.active);
function save(){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{note('El navegador no pudo guardar el progreso.',true)}}
function note(s,bad=false){statusEl.textContent=s;statusEl.className=bad?'err':'ok'}
async function api(route,payload){let c=new AbortController(),timer=setTimeout(()=>c.abort(),100000);try{let r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:c.signal});let d=await r.json();if(!r.ok)throw Error(d.error||'Error del servidor');return d}catch(e){if(e.name==='AbortError')throw Error('La solicitud tardó demasiado; revisa el servidor antes de repetir.');if(e instanceof TypeError)throw Error('No se pudo contactar al servidor local.');throw e}finally{clearTimeout(timer)}}
async function task(label,fn){if(busy)return;busy=true;note(label);try{await fn();if(statusEl.textContent===label)note('Listo.')}catch(e){note(e?.message||String(e),true);console.error(e)}finally{busy=false}}
function nav(){app.append(B('Mis metas',()=>{page='home';render()},true));if(g())app.append(B('Mi ruta',()=>{page='dashboard';render()},true))}
function backup(){let url=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'})),a=E('a');a.href=url;a.download='ruta-v4-respaldo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function home(){app.replaceChildren();let b=block('Una meta, no un curso genérico'),name=E('input'),context=E('textarea');name.placeholder='Ej. Entender el tratamiento superficial';context.placeholder='Opcional: experiencia previa, sin información interna';b.append(name,context,B('Empezar ruta',()=>task('Construyendo solo el mapa inicial…',async()=>{if(name.value.trim().length<5)throw Error('Escribe una meta más concreta.');let d=await api('/api/map',{goal:name.value.trim(),context:context.value.trim()});let goal={id:crypto.randomUUID(),goal:name.value.trim(),context:context.value.trim(),nodes:d.nodes,coverage:Array.isArray(d.coverage)?d.coverage:[],map_version:d.map_version||1,map_updates:[],learner:{},lessons:{},reviews:[],events:[],session:{mode:'DIAGNOSTIC',node:null,stack:[],stage:'teach',tries:0}};store.goals.push(goal);store.active=goal.id;save();page='session';render()})));
if(store.goals.length){let list=block('Mis metas');for(let x of store.goals)list.append(B(x.goal,()=>{store.active=x.id;page='dashboard';render()}),B('Eliminar',()=>{if(confirm('¿Eliminar esta meta y sus avances?')){store.goals=store.goals.filter(z=>z.id!==x.id);if(store.active===x.id)store.active=null;save();render()}},true),E('br'))}app.append(B('Exportar respaldo',backup,true));let input=E('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{let d=JSON.parse(await input.files[0].text());if(!Array.isArray(d.goals)||!d.goals.every(x=>x.id&&Array.isArray(x.nodes)&&x.learner&&x.session))throw Error('Este archivo no es un respaldo de Ruta v4.');if(!confirm('¿Reemplazar los datos v4 de este navegador por el respaldo?'))return;store=d;save();render()}catch(e){note(e.message,true)}};app.append(E('p','Restaurar respaldo v4 (reemplaza los datos actuales):'),input)}
function coverageOf(goal,id){goal.coverage=Array.isArray(goal.coverage)?goal.coverage:[];let c=goal.coverage.find(x=>x.id===id);if(!c){let n=goal.nodes.find(x=>x.id===id)||{name:id,kind:'concept',prerequisites:[]};c={id,name:n.name,kind:n.kind,priority:'important',prerequisites:n.prerequisites||[],contexts:[],status:'UNKNOWN',confidence:0,last_evidence:null,dimensions:[{id:'conceptual',name:'Comprensión',required:true,status:'UNKNOWN',evidence:[]},{id:'direct_application',name:'Aplicación',required:true,status:'UNKNOWN',evidence:[]}],updates:[]};goal.coverage.push(c)}c.dimensions=Array.isArray(c.dimensions)?c.dimensions:[];return c}
function state(goal,id){if(!goal.learner[id])goal.learner[id]={level:0,confidence:'unverified',evidence:[],errors:[],last:null};let s=goal.learner[id];s.evidence=Array.isArray(s.evidence)?s.evidence:[];s.errors=Array.isArray(s.errors)?s.errors:[];coverageOf(goal,id);return s}
const EVIDENCE_POLICY_VERSION='evidence_policy_v1';
const ALLOWED_DIMENSIONS=new Set(['conceptual','recognition','variables','units','equation_manipulation','method_selection','direct_application','contextual_application','interpretation','transfer','procedure','memory','self_explanation']);
const ACTIVITY_ROLES={
 diagnostic_probe:{stage:'DIAGNOSTIC',dimensions:['conceptual'],supports_independence:true},
 comprehension_check:{stage:'COMPREHENSION',dimensions:['conceptual'],supports_independence:false},
 guided_practice:{stage:'GUIDED',dimensions:['direct_application'],supports_independence:false},
 independent_practice:{stage:'INDEPENDENT',dimensions:['direct_application'],supports_independence:true},
 integration:{stage:'INTEGRATE',dimensions:['contextual_application','interpretation'],supports_independence:true},
 spaced_review:{stage:'REVIEW',dimensions:['memory'],supports_independence:true},
 microtutor_check:{stage:'MICRO_TUTOR',dimensions:['conceptual'],supports_independence:false},
 microtutor_guided:{stage:'MICRO_TUTOR',dimensions:['direct_application'],supports_independence:false},
 microtutor_independent:{stage:'MICRO_TUTOR',dimensions:['direct_application'],supports_independence:true},
};
function uniqueDimensions(values){return [...new Set((Array.isArray(values)?values:[]).filter(x=>ALLOWED_DIMENSIONS.has(x)))]}
function kindDimensions(kind){let k=String(kind||'').toLowerCase();if(/recognition|choice|multiple|matching|mcq/.test(k))return ['recognition'];if(/self.?explanation/.test(k))return ['conceptual','self_explanation'];if(/procedure/.test(k))return ['procedure','direct_application'];if(/calculation|problem|application|exercise/.test(k))return ['direct_application'];if(/recall|memory|retrieval/.test(k))return ['memory'];return ['conceptual']}
function newId(prefix){let value=globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);return prefix+'-'+value}
function normalizeActivityContract(raw={}){return {activity_id:raw.activity_id||newId('activity'),node_id:raw.node_id||null,stage:raw.stage||'UNKNOWN',kind:raw.kind||'unknown',observable_dimensions:uniqueDimensions(raw.observable_dimensions),supports_independence:raw.supports_independence===true,supports_transfer:raw.supports_transfer===true,variant_id:raw.variant_id||null,is_novel_variant:raw.is_novel_variant===true,help_policy:raw.help_policy||'any_help_blocks_independence',role:raw.role||'unspecified'}}
function activityContract(question={},nodeId,role){let policy=ACTIVITY_ROLES[role]||{stage:'UNKNOWN',dimensions:kindDimensions(question.kind),supports_independence:false};let explicit=question.activity_contract&&typeof question.activity_contract==='object'?question.activity_contract:{},hasIndependence=Object.prototype.hasOwnProperty.call(explicit,'supports_independence'),hasTransfer=Object.prototype.hasOwnProperty.call(explicit,'supports_transfer');let declared=Array.isArray(explicit.observable_dimensions)?explicit.observable_dimensions:Array.isArray(question.observable_dimensions)?question.observable_dimensions:uniqueDimensions([...policy.dimensions,...kindDimensions(question.kind)]);let novelty=explicit.is_novel_variant===true||question.is_novel_variant===true||Boolean(question.novelty_flags&&Object.values(question.novelty_flags).some(Boolean));return normalizeActivityContract({...explicit,activity_id:explicit.activity_id||question.activity_id||(question.activity_id=newId('activity')),node_id:nodeId,stage:explicit.stage||policy.stage,kind:explicit.kind||question.kind||'unknown',observable_dimensions:declared,supports_independence:hasIndependence?explicit.supports_independence===true:policy.supports_independence===true,supports_transfer:(hasTransfer?explicit.supports_transfer===true:question.supports_transfer===true)&&novelty,variant_id:explicit.variant_id||question.variant_id||null,is_novel_variant:novelty,role})}
function evidenceTargets(activity){return uniqueDimensions(activity&&activity.observable_dimensions)}
function activityEvidence(activity,assessment,help=0,meta={}){let contract=normalizeActivityContract(activity),result=assessment.status||'UNKNOWN',corrected=meta.corrected===true,helpUsed=Math.max(0,Number(help)||0),diagnostic=contract.stage==='DIAGNOSTIC'||contract.role==='diagnostic_probe',timestamp=meta.timestamp||Date.now();return {evidence_id:meta.evidence_id||newId('evidence'),attempt_id:meta.attempt_id||newId('attempt'),activity_id:contract.activity_id,node_id:contract.node_id,phase:contract.stage,activity_kind:contract.kind,result,status:result,help_used:helpUsed,help:helpUsed,is_independent:result==='CORRECT'&&contract.supports_independence&&helpUsed===0&&!corrected,independent:result==='CORRECT'&&contract.supports_independence&&helpUsed===0&&!corrected,is_novel_variant:contract.supports_transfer&&contract.is_novel_variant,varied:contract.supports_transfer&&contract.is_novel_variant,observed_dimensions:evidenceTargets(contract),error_type:assessment.error_type||'none',error:assessment.error_type||'none',counts_as_learning_failure:!diagnostic&&result!=='CORRECT',evidence_role:diagnostic?'diagnostic':'learning',evaluator_version:assessment.evaluator_version||(corrected?'user-correction-v1':'gemini-eval-v1'),corrected,original_result:meta.original_result||result,timestamp,at:timestamp,policy_version:EVIDENCE_POLICY_VERSION}}
function sufficient(d){let evidence=Array.isArray(d.evidence)?d.evidence:[],lastFailure=-1;for(let i=0;i<evidence.length;i++)if((evidence[i].result||evidence[i].status)!=='CORRECT')lastFailure=i;let recent=evidence.slice(lastFailure+1).filter(x=>(x.result||x.status)==='CORRECT');if(!recent.length)return false;if(d.id==='direct_application'||d.id==='procedure')return recent.some(x=>x.is_independent===true);if(d.id==='transfer')return recent.some(x=>x.is_independent===true&&x.is_novel_variant===true);if(d.id==='memory')return recent.some(x=>x.is_independent===true&&x.phase==='REVIEW');return true}
function deriveCoverage(c){let dimensions=(Array.isArray(c.dimensions)?c.dimensions:[]).map(d=>{let evidence=Array.isArray(d.evidence)?d.evidence:[],mastered=sufficient(d),hasCorrect=evidence.some(x=>(x.result||x.status)==='CORRECT');return {id:d.id,name:d.name||d.id,required:d.required!==false,status:mastered?'MASTERED':hasCorrect?'PARTIALLY_UNDERSTOOD':evidence.length?'LEARNING':'UNKNOWN',mastered}});let required=dimensions.filter(d=>d.required),done=required.filter(d=>d.mastered).length;return {dimensions,done,total:required.length,confidence:required.length?done/required.length:0,status:required.length&&done===required.length?'MASTERED':done?'PARTIALLY_UNDERSTOOD':dimensions.some(d=>d.status!=='UNKNOWN')?'LEARNING':'UNKNOWN',mastered:required.length>0&&done===required.length}}
function syncCoverage(c){let derived=deriveCoverage(c);for(let result of derived.dimensions){let d=c.dimensions.find(x=>x.id===result.id);if(d)d.status=result.status}c.confidence=derived.confidence;c.status=derived.status;return derived}
function updateCoverage(goal,id,event){let c=coverageOf(goal,id);for(let target of event.observed_dimensions){let d=c.dimensions.find(x=>x.id===target);if(!d)continue;d.evidence=Array.isArray(d.evidence)?d.evidence:[];d.evidence.push(event)}c.last_evidence=event.timestamp;return syncCoverage(c)}
function wasAttemptApplied(goal,attemptId){return Boolean(attemptId)&&Array.isArray(goal.events)&&goal.events.some(x=>x&&x.type==='EVIDENCE'&&x.attempt_id===attemptId)}
function record(goal,id,phase,answer,assessment,help=0,activity=null,attemptId=null){let contract=activity?normalizeActivityContract(activity):normalizeActivityContract({node_id:id,stage:phase,kind:'legacy_unspecified',observable_dimensions:['conceptual'],role:'legacy_unspecified'}),resolvedAttempt=attemptId||assessment._attempt_id||newId('attempt');if(wasAttemptApplied(goal,resolvedAttempt))return null;let event=activityEvidence(contract,assessment,help,{attempt_id:resolvedAttempt,corrected:assessment._corrected===true,original_result:assessment._original_status||assessment.status});event.answer=String(answer||'').slice(0,700);let s=state(goal,id);s.last=event.timestamp;s.evidence.push(event);if(event.counts_as_learning_failure)s.errors.push({at:event.timestamp,type:event.error_type||'unknown',phase:event.phase,attempt_id:event.attempt_id});goal.events=Array.isArray(goal.events)?goal.events:[];goal.events.push({type:'EVIDENCE',...event});updateCoverage(goal,id,event);save();return event}
function nextIntervention(goal,id,phase,result){let e=result?.error_type||'none',c=coverageOf(goal,id);if(result?.status==='CORRECT')return phase==='INTEGRATE'?'SPACED_REVIEW':'ADVANCE';if(e==='prerequisite')return 'PREREQUISITE';if(['algebra','arithmetic','units','formula_selection','variable_identification'].includes(e))return 'TARGETED_MICRO';if(e==='conceptual')return 'EXPLAIN_THEN_MICRO';if(e==='memory')return 'RETRIEVAL_REPAIR';if(e==='transfer'||e==='application')return 'CONTEXTUAL_PRACTICE';return c.status==='LEARNING'?'GUIDED_REPAIR':'TARGETED_MICRO'}
function originalQuestion(goal,id,phase){let l=goal.lessons[id];return phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:phase==='INTEGRATE'?l.integration:l.independent}
function openIntervention(goal,id,phase,answer,result){let decision=nextIntervention(goal,id,phase,result),q=originalQuestion(goal,id,phase);task('Preparando una intervención específica…',async()=>{let ctx=await api('/api/context/create',{question:q,answer,feedback:result.feedback});ctx.parent_context_id=null;ctx.parent_question=q;ctx.resume_mode=phase;ctx.decision=decision;ctx.origin_node=id;pushContext(goal,ctx);render()})}
const verified=(goal,id)=>deriveCoverage(coverageOf(goal,id)).mastered;
function relevant(goal){let nodes=goal.nodes,byId=Object.fromEntries(nodes.map(n=>[n.id,n]));let out=[];let open=new Set(nodes.map(n=>n.id));while(open.size){let ready=nodes.filter(n=>open.has(n.id)&&n.prerequisites.every(d=>!open.has(d)||!byId[d]));if(!ready.length)break;ready.sort((a,b)=>a.level-b.level);for(let n of ready){out.push(n);open.delete(n.id)}}return out}
function nextNode(goal){return relevant(goal).find(n=>!verified(goal,n.id))||null}
function masteredCount(goal){return goal.nodes.filter(n=>verified(goal,n.id)).length}
function nextLearningAction(goal){let s=goal.session;if(s.mode==='TEACH')return 'EXPLAIN';if(s.mode==='COMPREHENSION')return 'CHECK';if(s.mode==='GUIDED')return 'GUIDED_PRACTICE';if(s.mode==='INDEPENDENT')return 'INDEPENDENT_PRACTICE';if(s.mode==='INTEGRATE')return 'INTEGRATE_WITH_GOAL';if(s.mode==='REVIEW')return 'SPACED_REVIEW';return 'PROBE_PREREQUISITE'}
function prerequisite(goal,id,visited=new Set()){if(visited.has(id))return null;visited.add(id);let n=goal.nodes.find(n=>n.id===id);if(!n)return null;for(let dep of n.prerequisites){let prior=prerequisite(goal,dep,visited);if(prior)return prior;if(!verified(goal,dep))return dep}return null}
function startTeach(goal,id){let s=goal.session,dep=prerequisite(goal,id);if(dep&&dep!==id){if(!s.stack.includes(id))s.stack.push(id);id=dep}let known=state(goal,id);s.node=id;s.mode=known.level===0?'TEACH':'COMPREHENSION';s.stage='teach';s.tries=0;save();page='session';render()}
function nextAfterLesson(goal){let s=goal.session,prev=s.stack.pop();s.node=null;s.tries=0;if(prev&&!verified(goal,prev)){startTeach(goal,prev);return}s.mode='DIAGNOSTIC';save();render()}
function schedule(goal,id){if(!goal.reviews.some(x=>x.id===id))goal.reviews.push({id,due:Date.now()+DAY,step:0,question:null,history:[]});save()}
function dashboard(){let goal=g();if(!goal){page='home';render();return}app.replaceChildren();nav();let b=block(goal.goal),due=goal.reviews.filter(r=>r.due<=Date.now());b.append(E('p',`Hoy: ${due.length} repasos · ${masteredCount(goal)} habilidades demostradas · ${goal.nodes.length} en el mapa.`),B('Seguir aprendiendo',()=>{page='session';render()}),B(`Repasar (${due.length})`,()=>{if(!due.length){note('Aún no hay repasos pendientes.');return}goal.session.mode='REVIEW';goal.session.node=due[0].id;save();page='session';render()}));let list=block('Cobertura del objetivo');for(let n of relevant(goal)){let s=state(goal,n.id),c=coverageOf(goal,n.id),progress=deriveCoverage(c);list.append(E('p',`${progress.mastered?'✓':s.level?'→':'○'} ${n.name} · ${progress.status} · ${progress.dimensions.filter(d=>d.required).map(d=>d.id+':'+d.status).join(', ')} · ${n.outcome}`))}app.append(B('Guardar respaldo',backup,true))}
async function session(){let goal=g();if(!goal){page='home';render();return}let s=goal.session;app.replaceChildren();nav();let b=block(goal.goal),action=nextLearningAction(goal);
if(s.mode==='DIAGNOSTIC'){let n=nextNode(goal);if(!n){b.append(E('p','Por ahora recorrimos esta ruta. Puedes practicar y revisar conceptos después.'));return}s.node=n.id;save();let p=b.appendChild(E('p',`Antes de avanzar, veamos si ya conoces «${n.name}». Si nunca lo has visto, te lo enseño.`));renderQuestion(b,n.probe,n.id,'DIAGNOSTIC','diagnostic_probe');b.append(B('No sé; enséñamelo',()=>{let activity=activityContract(n.probe,n.id,'diagnostic_probe');record(goal,n.id,'DIAGNOSTIC','No sé',{status:'UNKNOWN',error_type:'lack_of_exposure'},0,activity,newId('attempt'));startTeach(goal,n.id)},true));return}
let n=goal.nodes.find(x=>x.id===s.node);if(!n){s.mode='DIAGNOSTIC';render();return}let coverage=coverageOf(goal,n.id),progress=deriveCoverage(coverage);b.append(E('p',`Ahora: ${n.name} · ${action}`),E('p',`Cobertura: ${progress.status} · ${progress.dimensions.filter(d=>d.required).map(d=>d.name+'='+d.status).join(', ')}`));if(s.mode==='REVIEW'){await reviewView(b,goal,n);return}
if(!goal.lessons[n.id]){b.append(E('p','Preparando solo esta microlección…'));await task('Preparando una explicación breve…',async()=>{let parent=s.stack[s.stack.length-1],p=goal.nodes.find(x=>x.id===parent);goal.lessons[n.id]=await api('/api/lesson',{goal:goal.goal,name:n.name,parent:p?.name||goal.goal});save();render()});return}
let l=goal.lessons[n.id];
if(s.mode==='TEACH'){b.append(E('h3','Una idea a la vez'),E('p',l.explanation),E('p','Ejemplo'),E('pre',l.example),E('p',`Error habitual: ${l.common_error}`));b.append(B('Ahora lo intento',()=>{s.mode='COMPREHENSION';state(goal,n.id).level=Math.max(1,state(goal,n.id).level);save();render()}));return}
let phase=s.mode,question=phase==='COMPREHENSION'?l.check:phase==='GUIDED'?l.guided:(phase==='INDEPENDENT'||phase==='CHALLENGE')?l.independent:l.integration,role=phase==='COMPREHENSION'?'comprehension_check':phase==='GUIDED'?'guided_practice':(phase==='INDEPENDENT'||phase==='CHALLENGE')?'independent_practice':'integration';
renderQuestion(b,question,n.id,phase,role);
if(phase==='GUIDED')b.append(B('Dame una pista',()=>{let x=E('p',`Pista: ${l.common_error} Piensa qué dato falta para decidir.`);b.append(x);s.hints=(s.hints||0)+1;save()},true));
if(phase==='COMPREHENSION')b.append(B('No lo entendí; vuelve al ejemplo',()=>{s.mode='TEACH';save();render()},true));
}
function renderQuestion(box,question,id,phase,role='unspecified'){
 let goal=g(),answer=E('textarea'),feedback=E('div'),activity=activityContract(question,id,role),attemptId=newId('attempt');box.append(E('h3',question.prompt));
 answer.placeholder='Tu idea y por qué. No hace falta que sea perfecta.';
 let submit=B('Compartir mi intento',()=>task('Analizando tu razonamiento…',async()=>{
  let text=answer.value.trim();if(!text)throw Error('Escribe una idea o elige «No sé».');
  let assessment=await api('/api/evaluate',{question,answer:text,phase,attempt_id:attemptId,activity});answer.disabled=true;
  feedback.replaceChildren(E('p',assessment.feedback));
  if(assessment.hint)feedback.append(E('p',`Pista: ${assessment.hint}`));
  let result=changes=>({...assessment,...changes,_attempt_id:attemptId,_activity:activity,_original_status:assessment.status});
  feedback.append(B('Continuar',()=>applyResult(goal,id,phase,text,result({_corrected:false}))));
  feedback.append(B('Corregir evaluación',()=>{let ok=confirm('¿Tu respuesta demuestra comprensión?');applyResult(goal,id,phase,text,result({status:ok?'CORRECT':'PARTIAL',_corrected:true}))},true));
 }));box.append(answer,submit,feedback)
}
function applyResult(goal,id,phase,answer,result){let s=goal.session,st=state(goal,id),activity=result._activity||null,event=record(goal,id,phase,answer,result,s.hints||0,activity,result._attempt_id||null);if(!event)return false;s.hints=0;st.confidence=verified(goal,id)?'verified':'unverified';if(phase==='REVIEW'){let r=goal.reviews.find(x=>x.id===id),was=r.question;r.history.push({at:Date.now(),prompt:was.prompt,pass:result.status==='CORRECT',attempt_id:event.attempt_id});r.step=result.status==='CORRECT'?Math.min(INTERVALS.length-1,r.step+1):0;r.due=Date.now()+INTERVALS[r.step]*DAY;r.question=null;s.mode='DIAGNOSTIC';save();if(result.status!=='CORRECT')startTeach(goal,id);else{page='dashboard';render()}return true}if(phase==='DIAGNOSTIC'){if(result.status==='CORRECT'){st.level=Math.max(st.level,3);s.mode='CHALLENGE';save();render()}else startTeach(goal,id);return true}if(result.status!=='CORRECT'){let decision=nextIntervention(goal,id,phase,result);goal.events.push({type:'TUTOR_DECISION',at:Date.now(),id,phase,decision,error:result.error_type||'none',attempt_id:event.attempt_id});save();openIntervention(goal,id,phase,answer,result);return true}s.tries=0;if(phase==='CHALLENGE'){st.level=5;s.mode='INTEGRATE'}else if(phase==='COMPREHENSION'){st.level=Math.max(st.level,3);s.mode='GUIDED'}else if(phase==='GUIDED'){st.level=Math.max(st.level,4);s.mode='INDEPENDENT'}else if(phase==='INDEPENDENT'){st.level=Math.max(st.level,5);s.mode='INTEGRATE'}else if(phase==='INTEGRATE'){st.level=6;st.confidence=verified(goal,id)?'verified':'unverified';schedule(goal,id);nextAfterLesson(goal);return true}save();render();return true}
async function reviewView(box,goal,n){let r=goal.reviews.find(x=>x.id===n.id);if(!r){goal.session.mode='DIAGNOSTIC';render();return}if(!r.question){try{let d=await api('/api/review',{goal:goal.goal,concept:n.name,level:r.step,previous:r.history.slice(-3).map(x=>x.prompt).join('; ')});r.question=d.question;save()}catch(e){note(e.message+' Reutilizaré un caso guardado.',true);r.question=goal.lessons[n.id]?.independent||n.probe;save()}}renderQuestion(box,r.question,n.id,'REVIEW','spaced_review');box.append(B('No recuerdo; volvamos a aprenderlo',()=>{r.due=Date.now()+DAY;r.step=0;r.question=null;save();startTeach(goal,n.id)},true))}


// Context stack: the top context alone is evaluated. Parents remain paused.
function contextStack(goal){if(!Array.isArray(goal.contextStack))goal.contextStack=[];return goal.contextStack}
function topContext(goal){let s=contextStack(goal);return s[s.length-1]}
function pushContext(goal,ctx){let s=contextStack(goal),parent=topContext(goal);if(parent){parent.status='PAUSED';ctx.parent_context_id=parent.context_id}ctx.status='ACTIVE';s.push(ctx);goal.session.mode='CONTEXT';save()}
function popContext(goal,mastery){let s=contextStack(goal),child=s.pop();if(child)child.status='MASTERED';let parent=topContext(goal);if(parent){parent.status='RETURNING';parent.history=parent.history||[];parent.history.push({child:child.context_id,mastery});goal.session.mode='CONTEXT'}else{goal.session.mode=child?.resume_mode||'DIAGNOSTIC'}save()}
function contextScreen(box,goal){
 let ctx=topContext(goal);if(!ctx){goal.session.mode='DIAGNOSTIC';save();render();return}
 ctx.history=Array.isArray(ctx.history)?ctx.history:[];ctx.attempts=Number.isFinite(ctx.attempts)?ctx.attempts:0;ctx.stage=ctx.stage||'CHECK';
 box.append(E('p',`Contexto activo: ${ctx.concept} · intervención: ${ctx.decision||'MICRO_TUTOR'}`),E('p',`Objetivo: ${ctx.objective}`));
 if(ctx.stage==='CHECK'){if(ctx.explanation)box.append(E('p',ctx.explanation));if(ctx.example)box.append(E('p',`Ejemplo trabajado: ${ctx.example}`))}
 let labels={CHECK:'Comprobación breve',GUIDED:'Práctica guiada: explica cada paso; usa la pista si la necesitas.',INDEPENDENT:'Práctica independiente: aplícalo en una respuesta completa.'};
 box.append(E('h3',labels[ctx.stage]||'Práctica'),E('p',ctx.question.prompt));
 let ans=E('textarea'),feedback=E('div');ans.placeholder='Explica tu razonamiento. Si necesitas ayuda, usa la pista.';box.append(ans);
 function hint(){let text=ctx.example||'Vuelve al principio y nombra el paso que conecta los datos con la respuesta.';feedback.append(E('p',`Pista: ${text}`));ctx.hints_used=(ctx.hints_used||0)+1;save()}
 function retry(){ctx.status='ACTIVE';save();render()}
 function advance(){if(ctx.stage==='CHECK'){ctx.stage='GUIDED';ctx.status='ACTIVE';save();render();return}if(ctx.stage==='GUIDED'){ctx.stage='INDEPENDENT';ctx.status='ACTIVE';save();render();return}ctx.status='MASTERED';ctx.mastery=(ctx.mastery||0)+1;save();popContext(goal,ctx.mastery);render()}
 let button=B('Evaluar esta práctica',()=>task('Evaluando la intervención…',async()=>{let text=ans.value.trim();if(!text)throw Error('Escribe una respuesta.');let r=await api('/api/context/step',{context:{...ctx,status:'ACTIVE'},answer:text});ctx.attempts++;ctx.history.push({stage:ctx.stage,question:ctx.question.prompt,answer:text,result:r,hints:ctx.hints_used||0});ans.disabled=true;button.disabled=true;feedback.replaceChildren(E('p',r.feedback||''));if(r.hint)feedback.append(E('p',`Pista: ${r.hint}`));if(r.status==='CORRECT'){feedback.append(B(ctx.stage==='INDEPENDENT'?'Volver al problema original':'Continuar',advance));}else{ctx.status='NEEDS_DECOMPOSITION';if((ctx.hints_used||0)===0)feedback.append(B('Dame una pista',hint,true));feedback.append(B('Intentar otra vez esta práctica',retry,true));if(contextStack(goal).length<4)feedback.append(B('Zoom: aislar un prerrequisito',()=>task('Creando contexto hijo…',async()=>{let child=await api('/api/context/zoom',{context:ctx,answer:text,feedback:r.feedback});pushContext(goal,child);render()})));save()}}));box.append(button);if(ctx.stage==='GUIDED')box.append(B('Dame una pista',hint,true));box.append(feedback)
}
function render(){note('');if(page==='home')home();else if(page==='dashboard')dashboard();else if(g()?.session?.mode==='CONTEXT'){app.replaceChildren();nav();let box=block(g().goal);contextScreen(box,g())}else session()}
if(typeof module!=='undefined'&&module.exports){module.exports={normalizeActivityContract,activityContract,evidenceTargets,activityEvidence,sufficient,deriveCoverage,updateCoverage,wasAttemptApplied,record,verified,nextNode,masteredCount,applyResult,EVIDENCE_POLICY_VERSION}}else render();

